### ISSUE TITLE
controller error: 'remaining connection slots are reserved for non-replication superuser connections'

### ISSUE THREAD

**Issue by Xe** [deis/deis#1619]
I was trying to recreate #1149 (old app release containers not removed from fleet) and I was using the following shell script to rapidly create and destroy containers:

``` console
$ for i in $(seq 1 20); do deis scale web=20 ; sleep 1 ; deis scale web=1 ; sleep 1 ; done
```

The error I got was:

```
2014-08-18 12:06:04 [10617] [DEBUG] GET /api/apps/nonfat-airfield/containers
2014-08-18 12:06:05 [10617] [DEBUG] POST /api/apps/nonfat-airfield/scale
[2014-08-18 12:06:05,698: INFO/MainProcess] Received task: api.tasks.start_containers[efc1e29b-c675-4860-ba2a-7642d799ff13]
[2014-08-18 12:06:05,724: WARNING/Worker-4] Exception in thread Thread-455:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/api/models.py", line 47, in _inner
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_fsm/__init__.py", line 267, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_fsm/__init__.py", line 171, in change_state
    post_transition.send(**signal_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/api/models.py", line 714, in _save_transition
    kwargs['instance'].save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 570, in save_base
    with transaction.commit_on_success_unless_managed(using=using, savepoint=False):
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 532, in commit_on_success_unless_managed
    if connection.get_autocommit() or connection.in_atomic_block:
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 331, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopghttps://github.com/kennethreitz/django-postgrespool2/base.py", line 114, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
[2014-08-18 12:06:05,740: WARNING/Worker-4] Exception in thread Thread-459:
```

Except with a lot of instances of it over and over, happening on both creation and destruction. I think this might be an issue with the controller not using [connection pooling](https://stackoverflow.com/questions/11847144/heroku-psql-fatal-remaining-connection-slots-are-reserved-for-non-replication) and I have found [this python module](https://github.com/kennethreitz/django-postgrespool) that claims to be a connection pool for django and postgres.

Thoughts?

**Comment by MaxenceAdnot** [comment]
Sorry for reopening this issue.

I tried to stress test my running env on AWS and the same error appeared while trying to scale down an app currently running 700 web processes.

My ceph-less cluster on AWS:
3 Control Plane / Router Mesh hosts - t2.medium with gp2 storage (ssd)
3 Data Plane hosts - m4.large with gp2 storage (ssd)
The storage is running on S3 and the database on a t2.micro RDS instance. 

I'm using the version 1.10.0-dev for the deisctl utility and the controller is running on the image deisci/controller:jenkins-test-ec2-2847 (latest stable according to jenkins at this time)

The placement options are working properly and my 700 web processes are distributed across my 3 "data plane" hosts. These hosts are under very heavy load I admit it but I don't understand this error on the controller component. Restarting the controller doesn't change anything. The app continue to run (quite slowly because of the load but running anyway) but I can't scale the app down (503 SERVICE UNAVAILABLE Detail: aborting, failed to destroy some containers). 

The database and the control plane hosts doesn't seem to be loaded in any way. 

New Relic Server of the hosts (except SRV-VIRTUDEVOPS):
<img width="1068" alt="capture d ecran 2015-08-19 a 06 33 07" src="https://cloud.githubusercontent.com/assets/1312130/9348785/34fb9eae-463c-11e5-82d5-3c78fe5c9acc.png">

I can also send you the papertrails logs if needed.
