### ISSUE TITLE
[cli] locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by fgrehm** [deis/deis#1848]
From Ubuntu 14.04 using the CLI from https://s3-us-west-2.amazonaws.com/opdemand/deis-ubuntu-dev.tgz

```
$ deis
Traceback (most recent call last):
  File "<string>", line 74, in <module>
  File "/home/jenkins/workspace/build-deis-cli-ubuntu/client/build/deis/out00-PYZ.pyz/locale", line 579, in setlocale
locale.Error: unsupported locale setting
```

I'm happy to provide more information for further debugging :-)

**Comment by rogerleite** [comment]
@fgrehm thanks a lot. I had the same issue, I owe a :beer:.

**Comment by azurewraith** [comment]
Also ran into this, ironically on the heroku ruby buildpack built and deployed on Deis.

```
2015-08-23T23:59:17UTC api[web.1]:   File "/var/lib/jenkins/jobs/build-deis-cli-installer-linux/workspace/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/locale", line 579, in setlocale
2015-08-23T23:59:17UTC api[web.1]: locale.Error: unsupported locale setting
```

However, that environment does not allow you to change your locale to en_US.UTF-8:

```
slug@deab043cc24f:~$ export LANG=en_US.UTF-8
slug@deab043cc24f:~$ export LC_ALL=en_US.UTF-8
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
slug@deab043cc24f:~$ ~/bin/deis
Traceback (most recent call last):
  File "<string>", line 89, in <module>
  File "/var/lib/jenkins/jobs/build-deis-cli-installer-linux/workspace/src/github.com/deis/deis/client/build/deis/out00-PYZ.pyz/locale", line 579, in setlocale
locale.Error: unsupported locale setting
```

It is apparently just called something different in that slug environment:

```
slug@deab043cc24f:~$ locale -a
C
C.UTF-8
POSIX
```

Then things seem to work.  Chronicling for future adventurers.

```
slug@deab043cc24f:~$ export LC_ALL=C.UTF-8
slug@deab043cc24f:~$ ~/bin/deis
Usage: deis <command> [<args>...]
```
