### ISSUE TITLE
berks command failed to execute

### ISSUE THREAD

**Issue by dalekurt** [deis/deis#2553]
I'm setting this up on OS X with vagrant (version 1.6.5) and the following vagrant plugins

vagrant-berkshelf (4.0.0)
vagrant-cachier (1.1.0)
vagrant-hosts (2.2.3)
vagrant-login (1.0.1, system)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.2, system)

``` text
The following berks command failed to execute:

    /Volumes/MacintoshHDD/Users/dalekurt/.rbenv/shims/berks --version --format json

The stdout and stderr are shown below:

    stdout:
    stderr: /Volumes/MacintoshHDD/Users/dalekurt/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'berkshelf' (>= 0) among 60 total gem(s) (Gem::LoadError)
    from /Volumes/MacintoshHDD/Users/dalekurt/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
    from /Volumes/MacintoshHDD/Users/dalekurt/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Volumes/MacintoshHDD/Users/dalekurt/.rbenv/versions/2.1.4/bin/berks:22:in `<main>'


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.

Please download and install the latest version of the ChefDK from:

    https://downloads.getchef.com/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

**Comment by erupenkman** [comment]
I had the same issue and got it working by doing
brew cask uninstall chefdk
brew cask install chefdk

I also uninstalled the berkshelf( and other related gems) and uninstalled each version of ruby managed by RVM but it didn't work until I re-installed chefdk

**Comment by jarrettj** [comment]
@dalekurt Thanks. That helped. Uninstalled berkshelf and installed chef-dk.
