### ISSUE TITLE
500 error response when attempting to execute a command on a running app/container

### ISSUE THREAD

**Issue by renegare** [deis/deis#2614]
Steps to reproduce in terminal (using a vagrant setup):

```
$ deis --version
> 1.0.2

$ deis login http://deis.local3.deisapp.com
$ deis create php --no-remote
$ deis pull -a php php:5.6-apache
$ deis run -a php -- ls
> Running `ls`...
> 500 INTERNAL SERVER ERROR
> <h1>Server Error (500)</h1>
```

Here is the controller log of the steps carried out above (stack trace at the end):

```
Nov 29 17:08:09 deis-3 sh[3375]: 172.17.8.101 "POST /v1/auth/login/ HTTP/1.0" 200 - "python-requests/2.4.3 CPython/2.7.5 Darwin/14.0.0"
Nov 29 17:08:18 deis-3 sh[3375]: INFO php: config php-34cadf5 updated
Nov 29 17:08:18 deis-3 sh[3375]: INFO php: release php-v1 created
Nov 29 17:08:18 deis-3 sh[3375]: 172.17.8.100 "POST /v1/apps HTTP/1.0" 201 - "python-requests/2.4.3 CPython/2.7.5 Darwin/14.0.0"
Nov 29 17:08:27 deis-3 sh[3375]: INFO php: build php-0cee8a4 created
Nov 29 17:08:27 deis-3 sh[3375]: INFO php: release php-v2 created
Nov 29 17:08:31 deis-3 sh[3375]: INFO php: renegare scaled containers cmd=1
Nov 29 17:08:41 deis-3 sh[3375]: 172.17.8.100 "POST /v1/apps/php/builds HTTP/1.0" 201 - "python-requests/2.4.3 CPython/2.7.5 Darwin/14.0.0"
Nov 29 17:08:47 deis-3 sh[3375]: INFO php: renegare runs 'ls'
Nov 29 17:08:48 deis-3 sh[3375]: ERROR php: php_v2.run.1 (run): Authentication failed.
Nov 29 17:08:48 deis-3 sh[3375]: ERROR Internal Server Error: /v1/apps/php/run
Nov 29 17:08:48 deis-3 sh[3375]: Traceback (most recent call last):
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
Nov 29 17:08:48 deis-3 sh[3375]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Nov 29 17:08:48 deis-3 sh[3375]: return view_func(*args, **kwargs)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 79, in view
Nov 29 17:08:48 deis-3 sh[3375]: return self.dispatch(request, *args, **kwargs)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 403, in dispatch
Nov 29 17:08:48 deis-3 sh[3375]: response = self.handle_exception(exc)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 400, in dispatch
Nov 29 17:08:48 deis-3 sh[3375]: response = handler(request, *args, **kwargs)
Nov 29 17:08:48 deis-3 sh[3375]: File "/app/api/views.py", line 210, in run
Nov 29 17:08:48 deis-3 sh[3375]: output_and_rc = app.run(self.request.user, command)
Nov 29 17:08:48 deis-3 sh[3375]: File "/app/api/models.py", line 344, in run
Nov 29 17:08:48 deis-3 sh[3375]: return c.run(escaped_command)
Nov 29 17:08:48 deis-3 sh[3375]: File "/app/api/models.py", line 482, in run
Nov 29 17:08:48 deis-3 sh[3375]: rc, output = self._scheduler.run(job_id, image, entrypoint, command)
Nov 29 17:08:48 deis-3 sh[3375]: File "/app/scheduler/fleet.py", line 227, in run
Nov 29 17:08:48 deis-3 sh[3375]: ssh.connect(primaryIP, username="core", pkey=pkey)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 273, in connect
Nov 29 17:08:48 deis-3 sh[3375]: self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
Nov 29 17:08:48 deis-3 sh[3375]: File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 456, in _auth
Nov 29 17:08:48 deis-3 sh[3375]: raise saved_exception
Nov 29 17:08:48 deis-3 sh[3375]: AuthenticationException: Authentication failed.
Nov 29 17:08:48 deis-3 sh[3375]: 172.17.8.100 "POST /v1/apps/php/run HTTP/1.0" 500 - "python-requests/2.4.3 CPython/2.7.5 Darwin/14.0.0"
```

One last thing I tried was to journal the `php` app, I got a few things which seemed interesting but unclear:

```
Nov 29 17:03:29 deis-3 docker[15372]: php_v2.cmd.1
Nov 29 17:08:34 deis-3 systemd[1]: Starting php_v2.cmd.1...
Nov 29 17:08:36 deis-3 sh[17091]: Pulling repository 172.17.8.102:5000/php
Nov 29 17:08:40 deis-3 sh[17091]: Status: Downloaded newer image for 172.17.8.102:5000/php:v2
Nov 29 17:08:40 deis-3 systemd[1]: Started php_v2.cmd.1.
Nov 29 17:08:41 deis-3 sh[17161]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.0.12. Set the 'ServerName' directive globally to suppress this message
Nov 29 17:08:41 deis-3 sh[17161]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.1.0.12. Set the 'ServerName' directive globally to suppress this message
Nov 29 17:08:41 deis-3 sh[17161]: [Sat Nov 29 17:08:41.266223 2014] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.3 configured -- resuming normal operations
Nov 29 17:08:41 deis-3 sh[17161]: [Sat Nov 29 17:08:41.267312 2014] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
Nov 29 17:09:26 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:26 +0000] "GET / HTTP/1.1" 200 3390 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:27 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:27 +0000] "GET /icons/openlogo-75.png HTTP/1.1" 200 6014 "http://php.local.deisapp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:27 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:27 +0000] "GET / HTTP/1.1" 200 3390 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:27 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:27 +0000] "GET /icons/openlogo-75.png HTTP/1.1" 200 6014 "http://php.local.deisapp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:28 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:28 +0000] "GET / HTTP/1.1" 200 3390 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:28 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:28 +0000] "GET /icons/openlogo-75.png HTTP/1.1" 200 6014 "http://php.local.deisapp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:31 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:31 +0000] "GET / HTTP/1.1" 200 3390 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Nov 29 17:09:31 deis-3 sh[17161]: 172.17.8.100 - - [29/Nov/2014:17:09:31 +0000] "GET /icons/openlogo-75.png HTTP/1.1" 200 6014 "http://php.local.deisapp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"

^C-- Logs begin at Sat 2014-11-29 14:26:36 UTC. --
Nov 29 16:29:17 deis-2 systemd[1]: Starting php_v2.run.1 admin command...
Nov 29 16:29:19 deis-2 sh[4716]: Pulling repository 172.17.8.102:5000/php
Nov 29 16:29:19 deis-2 sh[4716]: Status: Image is up to date for 172.17.8.102:5000/php:v2
Nov 29 16:29:19 deis-2 systemd[1]: Started php_v2.run.1 admin command.
Nov 29 16:29:19 deis-2 sh[4757]: total 8
Nov 29 16:29:19 deis-2 sh[4757]: drwxr-xr-x 1 root root  64 Nov 28 15:01 .
Nov 29 16:29:19 deis-2 sh[4757]: drwxr-xr-x 1 root root   8 Nov 28 14:58 ..
Nov 29 16:29:19 deis-2 sh[4757]: -rw-r--r-- 1 root root 867 Nov 28 14:58 index.nginx-debian.html
Nov 29 16:29:19 deis-2 sh[4757]: -rw-r--r-- 1 root root  20 Nov 28 15:01 index.php

^C-- Logs begin at Sat 2014-11-29 14:26:12 UTC. --
Nov 29 16:55:42 deis-1 systemd[1]: Starting php_v2.run.2 admin command...
Nov 29 16:55:44 deis-1 sh[2483]: Pulling repository 172.17.8.102:5000/php
Nov 29 16:56:40 deis-1 sh[2483]: Status: Downloaded newer image for 172.17.8.102:5000/php:v2
Nov 29 16:56:40 deis-1 systemd[1]: Started php_v2.run.2 admin command.
Nov 29 16:56:40 deis-1 sh[3234]: total 12
Nov 29 16:56:40 deis-1 sh[3234]: drwxr-xr-x 1 www-data www-data    20 Nov 13 01:25 .
Nov 29 16:56:40 deis-1 sh[3234]: drwxr-xr-x 1 root     root         8 Nov 13 01:25 ..
Nov 29 16:56:40 deis-1 sh[3234]: -rw-r--r-- 1 root     root     11104 Nov 13 01:25 index.html

^C-- Logs begin at Sat 2014-11-29 14:26:36 UTC. --
Nov 29 16:58:44 deis-2 systemd[1]: Starting php_v2.run.3 admin command...
Nov 29 16:58:46 deis-2 sh[5168]: Pulling repository 172.17.8.102:5000/php
Nov 29 16:59:38 deis-2 sh[5168]: Status: Downloaded newer image for 172.17.8.102:5000/php:v2
Nov 29 16:59:39 deis-2 systemd[1]: Started php_v2.run.3 admin command.
Nov 29 16:59:39 deis-2 sh[5406]: index.html
```

^^^ note the `^C`, I had to hit `ctrl+c` several times to exit the journal command and it appeared to print out more logs that appear to be the output of my 500 error run command.

Any thoughts (or better solution) would be much appreciated :)

**Comment by ineu** [comment]
@bacongobbler Sorry for writing in the old ticket, but just a quick question: do I understand it correctly that `deis run` is only available to a single user, whose private key is stored in the `/deis/platform/sshPrivateKey`? So no other users, even those able to deploy an app, cannot execute `deis run`?

**Comment by bacongobbler** [comment]
No. Everyone is able to use it. Every call for `deis run` on fleet uses `/deis/platform/sshPrivateKey` as the SSH key to log into the CoreOS server and retrieve the output. It's a server-side implementation detail.
