### ISSUE TITLE
bug(database): the backup should not interfere the etcd publication

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2741]
If the backup time is bigger than the etcd timeout the database becomes unavailable.
A side effect of this is that the service status is ok (active - running) without any flapping.

This is the output from a node with this problem:
```
  PID TTY      STAT   TIME COMMAND
24393 ?        S      0:00 -bash
24501 ?        R+     0:00  \_ ps axf
    1 ?        Ss     0:00 /bin/bash /app/bin/boot
  110 ?        S      0:00 sudo -i -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config-file=/etc/postgresql/9.3/main/postgresql.conf -c listen-addresses=*
  117 ?        S      0:00  \_ /usr/lib/postgresql/9.3/bin/postgres -c config-file=/etc/postgresql/9.3/main/postgresql.conf -c listen-addresses=*
  120 ?        Ss     0:01      \_ postgres: checkpointer process
  121 ?        Ss     0:00      \_ postgres: writer process
  122 ?        Ss     0:00      \_ postgres: wal writer process
  123 ?        Ss     0:00      \_ postgres: autovacuum launcher process
  124 ?        Ss     0:00      \_ postgres: archiver process   last was 000000020000000400000044
  125 ?        Ss     0:00      \_ postgres: stats collector process
  111 ?        Sl     1:03 confd -node 192.168.2.201:4001 -config-file /app/confd.toml
 4867 ?        S      0:00 sudo -u postgres envdir /etc/wal-e.d/env wal-e delete --confirm retain 5
 4868 ?        Sl     0:05  \_ /usr/bin/python /usr/local/bin/wal-e delete --confirm retain 5
```

How is possible to reproduce this? 
Any timeout during the upload of the backup ( `wal-e`) produces this output:
https://gist.github.com/aledbf/43e2c19344f812f7411f
wal-e retry the upload and it waits forever

This behavior avoids the periodic publication of the host/port in etcd
`https://github.com/deis/deis/blob/master/database/bin/boot#L147`

#2701 solves this behavior

**Comment by ineu** [comment]
On Deis 1.4.1 I encounter this issue every day. Any workaround to avoid it before it is fixed?

**Comment by bacongobbler** [comment]
> #2701 solves this behavior

**Comment by carmstrong** [comment]
> On Deis 1.4.1 I encounter this issue every day.

Can you share any information on the circumstances that lead to this for you? Are your backups large, or is wal-e unable to write to the gateway component? 

We need to address this in the backup loop logic, but there must be something else happening in your cluster to cause it to happen so regularly.

**Comment by ineu** [comment]
@carmstrong I don't think they are large, as the cluster was created about a week ago and doesn't run too many services.
The output from the deis-database:
```
        STRUCTURED: time=2015-03-20T05:30:10.238451-00 pid=31936
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2015-03-20T05:30:49.508797-00 pid=3764
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/0000000100000009000000A7" to "s3://db_wal/wal_005/0000000100000009000000A7.lzo".
        STRUCTURED: time=2015-03-20T05:30:49.531599-00 pid=3764 action=push-wal key=s3://db_wal/wal_005/0000000100000009000000A7.lzo prefix= seg=0000000100000009000000A7 state=begin
wal_e.worker.upload INFO     MSG: completed archiving to a file
        DETAIL: Archiving to "s3://db_wal/wal_005/0000000100000009000000A7.lzo" complete at 127.239KiB/s.
        STRUCTURED: time=2015-03-20T05:30:50.531644-00 pid=3764 action=push-wal key=s3://db_wal/wal_005/0000000100000009000000A7.lzo prefix= rate=127.239 seg=0000000100000009000000A7 state=complete
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
            bucket.delete_keys([key.name for key in page])
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
            while delete_keys2(headers):
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
            data=data)
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
            retry_handler=retry_handler
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
            retry_handler=retry_handler)
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
            raise ex
        timeout: timed out
```
repeating before component is restarted.
As for the gateway, it emits following:
```
Mar 20 05:20:28 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [10925858]
Mar 20 05:20:48 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [10926339]
Mar 20 05:21:35 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [10927527]
Mar 20 05:22:02 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [10928156]
Mar 20 05:24:15 staging-coreos-2 sh[2577]: Error:  100: Key not found (/deis/store/gateway/masterLock) [10931483]
```
Timestamps generally match time when database starts throwing exceptions.
According to `journalctl -u etcd` on all cluster members, there were no network splits/quorum losses.
