### ISSUE TITLE
race condition: registry fails to boot

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2833]
Saw this when booting up a new cluster:

```
core@deis-1 ~ $ docker logs deis-registry
2015-01-02T23:17:32Z 65a996ab62e2 confd[36]: ERROR exit status 1
registry: waiting for confd to write initial templates...
deis-registry running...
2015-01-02T23:17:40Z 65a996ab62e2 confd[60]: ERROR exit status 1
2015-01-02 23:17:41 [75] [INFO] Starting gunicorn 19.1.0
2015-01-02 23:17:41 [75] [INFO] Listening at: http://0.0.0.0:5000 (75)
2015-01-02 23:17:41 [75] [INFO] Using worker: gevent
2015-01-02 23:17:41 [82] [INFO] Booting worker with pid: 82
2015-01-02 23:17:41 [83] [INFO] Booting worker with pid: 83
2015-01-02 23:17:41 [88] [INFO] Booting worker with pid: 88
2015-01-02 23:17:41 [91] [INFO] Booting worker with pid: 91
02/Jan/2015:23:17:41 +0000 INFO: Enabling storage cache on Redis
02/Jan/2015:23:17:41 +0000 INFO: Redis host: 10.21.12.2:None (db1)
2015-01-02 23:17:41 [82] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
2015-01-02 23:17:41 [82] [INFO] Worker exiting (pid: 82)
2015-01-02 23:17:41 [75] [INFO] 4 workers
02/Jan/2015:23:17:41 +0000 INFO: Enabling storage cache on Redis
02/Jan/2015:23:17:41 +0000 INFO: Redis host: 10.21.12.2:None (db1)
2015-01-02 23:17:41 [83] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
2015-01-02 23:17:41 [83] [INFO] Worker exiting (pid: 83)
02/Jan/2015:23:17:41 +0000 INFO: Enabling storage cache on Redis
02/Jan/2015:23:17:41 +0000 INFO: Redis host: 10.21.12.2:None (db1)
2015-01-02 23:17:41 [88] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
2015-01-02 23:17:41 [88] [INFO] Worker exiting (pid: 88)
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 196, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 292, in halt
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 343, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
02/Jan/2015:23:17:41 +0000 INFO: Enabling storage cache on Redis
02/Jan/2015:23:17:41 +0000 INFO: Redis host: 10.21.12.2:None (db1)
2015-01-02 23:17:41 [91] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
    from .app import app  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
    from .lib import mirroring  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
    from . import cache
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
    init()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
    enable_redis_cache(cfg.cache, cfg.storage_path)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
    port=int(cache.port),
TypeError: int() argument must be a string or a number, not 'NoneType'
2015-01-02 23:17:41 [91] [INFO] Worker exiting (pid: 91)
2015-01-02T23:17:45Z 65a996ab62e2 confd[60]: ERROR exit status 1
```

Kicking the tires with `deisctl restart registry@1` did the trick, and the registry started publishing itself to etcd again.

**Comment by bacongobbler** [comment]
still seeing this issue on master. It seems to occur when etcd is not responding, typically due to latency issues:

```
Jan 05 23:31:41 deis-1 sh[3929]: 2015-01-05T23:31:41Z c184e05b4f5d confd[3919]: ERROR Config check failed: exit status 1
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [3983] [INFO] 4 workers
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [3983] [INFO] Handling signal: hup
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [3983] [INFO] Hang up: Master
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [13909] [INFO] Booting worker with pid: 13909
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [13910] [INFO] Booting worker with pid: 13910
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [13911] [INFO] Booting worker with pid: 13911
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [3983] [INFO] 4 workers
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [13912] [INFO] Booting worker with pid: 13912
Jan 05 23:31:46 deis-1 sh[3929]: 2015-01-05 23:31:46 [3983] [INFO] 4 workers
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Enabling storage cache on Redis
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Enabling storage cache on Redis
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Redis host: 172.17.8.100:None (db1)
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Enabling storage cache on Redis
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Redis host: 172.17.8.100:None (db1)
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Redis host: 172.17.8.100:None (db1)
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Enabling storage cache on Redis
Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Redis host: 172.17.8.100:None (db1)
Jan 05 23:31:48 deis-1 sh[3929]: 2015-01-05 23:31:48 [13912] [ERROR] Exception in worker process:
Jan 05 23:31:48 deis-1 sh[3929]: Traceback (most recent call last):
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
Jan 05 23:31:48 deis-1 sh[3929]: worker.init_process()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
Jan 05 23:31:48 deis-1 sh[3929]: super(GeventWorker, self).init_process()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
Jan 05 23:31:48 deis-1 sh[3929]: self.wsgi = self.app.wsgi()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
Jan 05 23:31:48 deis-1 sh[3929]: self.callable = self.load()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
Jan 05 23:31:48 deis-1 sh[3929]: return self.load_wsgiapp()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
Jan 05 23:31:48 deis-1 sh[3929]: return util.import_app(self.app_uri)
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
Jan 05 23:31:48 deis-1 sh[3929]: __import__(module)
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 19, in <module>
Jan 05 23:31:48 deis-1 sh[3929]: from .app import app  # noqa
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/app.py", line 22, in <module>
Jan 05 23:31:48 deis-1 sh[3929]: from .lib import mirroring  # noqa
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/mirroring.py", line 11, in <module>
Jan 05 23:31:48 deis-1 sh[3929]: from . import cache
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 60, in <module>
Jan 05 23:31:48 deis-1 sh[3929]: init()
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 20, in init
Jan 05 23:31:48 deis-1 sh[3929]: enable_redis_cache(cfg.cache, cfg.storage_path)
Jan 05 23:31:48 deis-1 sh[3929]: File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/cache.py", line 36, in enable_redis_cache
Jan 05 23:31:48 deis-1 sh[3929]: port=int(cache.port),
```

Note

> Jan 05 23:31:48 deis-1 sh[3929]: 05/Jan/2015:23:31:48 +0000 INFO: Redis host: 172.17.8.100:None (db1)

**Comment by carmstrong** [comment]
Looks like this has been happening for quite some time - #1885.

**Comment by carmstrong** [comment]
@gabrtv Suggests implementing this in a check script so we bail and don't let the config get written with a bad cache/port.

**Comment by carmstrong** [comment]
We think we can wrap the whole cache and cache LRU config directives in a check to ensure the host/port is valid.

**Comment by bacongobbler** [comment]
What strikes me as odd here is that the host IP address was written out correctly, but not the port. Maybe something to do with our registry master lock scheme?

In either case, this issue seems to have gone away now that we start the cache before we start the registry.
