### ISSUE TITLE
Database service recognition failed (boto timeout)

### ISSUE THREAD

**Issue by suquant** [deis/deis#2894]
In deis/database/bin/boot
Database service recognition failed
Because this does not work etcdctl set /deis/database/{host and port} ...

```
STRUCTURED: time=2015-01-14T02:48:52.524374-00 pid=31225
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
            bucket.delete_keys([key.name for key in page])
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
            while delete_keys2(headers):
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
            data=data)
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
            retry_handler=retry_handler
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
            retry_handler=retry_handler)
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
            raise ex
        timeout: timed out
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

**Comment by bacongobbler** [comment]
a boto exception would mean that the database failed connecting to ceph. Could you please post the health of your cluster, particularly deis-store-gateway?

**Comment by suquant** [comment]
deis version 1.2.0
run deisctl list output for all services "loaded active running"

dockel logs from deis-store-gateway 

```
Starting RADOS gateway...
Starting client.radosgw.gateway...
2015-01-13 11:05:21.765179 7f5ba82b8840  0 ceph version 0.87 (c51c8f9d80fa4e0168aa52685b8de40e42758578), process radosgw, pid 122
/usr/bin/radosgw is running.
Starting Apache...
deis-store-gateway running...

```

Also i use ceph (deis-store-gateway) in other django project, and then it work normally
I think this is due to the large wal file and because of the fact that the boto has no time to send the file to store in 30 seconds (timeout=30s) see https://github.com/wal-e/wal-e/blob/81a25d56e990c20d446eff472ad70c6efb923db8/wal_e/worker/pg/wal_transfer.py#L142

**Comment by suquant** [comment]
I think need create other executable file, for example 'database/bin/walbackup' and import there backup logic and run it into boot in background mode './walbackup &' :)

**Comment by carmstrong** [comment]
@suquant How much data are we talking here? The WAL would have to be pretty big to not complete in 30s. 

But you're right - we need to address that. See #2741.

**Comment by suquant** [comment]
ls -lah in pg_xlog

```
total 145M
drwx------ 1 101 106 584 Jan 14 03:37 .
drwx------ 1 101 106 388 Jan 13 14:47 ..
drwx------ 1 101 106  16 Jan 11 01:46 .wal-e
-rw------- 1 101 106  42 Jan 11 03:07 00000002.history
-rw------- 1 101 106 332 Jan 13 14:47 0000000200000005000000DF.00000028.backup
-rw------- 1 101 106 16M Jan 14 03:33 000000020000000600000078
-rw------- 1 101 106 16M Jan 14 03:37 000000020000000600000079
-rw------- 1 101 106 16M Jan 14 02:57 00000002000000060000007A
-rw------- 1 101 106 16M Jan 14 03:02 00000002000000060000007B
-rw------- 1 101 106 16M Jan 14 03:07 00000002000000060000007C
-rw------- 1 101 106 16M Jan 14 03:12 00000002000000060000007D
-rw------- 1 101 106 16M Jan 14 03:17 00000002000000060000007E
-rw------- 1 101 106 16M Jan 14 03:22 00000002000000060000007F
-rw------- 1 101 106 16M Jan 14 03:27 000000020000000600000080
drwx------ 1 101 106 190 Jan 14 03:37 archive_status
```

**Comment by suquant** [comment]
Once again
just noticed that the timeout arrives at the delete keys :/ 
WTF ...

```
STRUCTURED: time=2015-01-14T03:37:01.048553-00 pid=31225
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2015-01-14T03:38:01.189975-00 pid=1373
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/000000020000000600000079" to "s3://db_wal/wal_005/000000020000000600000079.lzo".
        STRUCTURED: time=2015-01-14T03:38:01.198852-00 pid=1373 action=push-wal key=s3://db_wal/wal_005/000000020000000600000079.lzo prefix= seg=000000020000000600000079 state=begin
wal_e.worker.upload INFO     MSG: completed archiving to a file 
        DETAIL: Archiving to "s3://db_wal/wal_005/000000020000000600000079.lzo" complete at 46.5657KiB/s. 
        STRUCTURED: time=2015-01-14T03:38:03.857892-00 pid=1373 action=push-wal key=s3://db_wal/wal_005/000000020000000600000079.lzo prefix= rate=46.5657 seg=000000020000000600000079 state=complete
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump: 
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
            bucket.delete_keys([key.name for key in page])
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
            while delete_keys2(headers):
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
            data=data)
          File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
            retry_handler=retry_handler
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
            retry_handler=retry_handler)
          File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
            raise ex
        timeout: timed out
        
        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
```

**Comment by carmstrong** [comment]
> I think need create other executable file, for example 'database/bin/walbackup' and import there backup logic and run it into boot in background mode './walbackup &' :)

Yep, something like that is definitely planned for #2741!

**Comment by carmstrong** [comment]
@suquant We're tracking this in #2741 and is definitely something we need to fix. Thanks for reporting, and sorry for the trouble!
