### ISSUE TITLE
Registration through API on 1.4.0 return internal server error

### ISSUE THREAD

**Issue by daemonza** [deis/deis#3185]
Running the following

        curl -i -X POST \
         -H "Content-Type: application/json" \
          -d '{"username":"demouser","password":"123"}' \
         http://DEIS/v1/auth/register/

as per the documentation here : 
http://docs.deis.io/en/latest/reference/api-v1.1/

I get the following : 

    HTTP/1.1 500 INTERNAL SERVER ERROR
    Content-Type: text/html
    Date: Wed, 04 Mar 2015 15:33:44 GMT
    Server: nginx/1.6.2
    X_DEIS_API_VERSION: 1.1
    X_DEIS_PLATFORM_VERSION: 1.4.0
    transfer-encoding: chunked
    Connection: keep-alive
    Server Error (500)

Running fleetctl journal on the controller this is the error that comes back : 

```
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: ERROR Internal Server Error: /v1/auth/register/
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: Traceback (most recent call last):
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return view_func(*args, **kwargs)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 85, in view
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return self.dispatch(request, *args, **kwargs)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: response = self.handle_exception(exc)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: response = handler(request, *args, **kwargs)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: self.perform_create(serializer)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 26, in perform_create
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: serializer.save()
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 164, in save
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: self.instance = self.create(validated_data)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/app/api/serializers.py", line 82, in create
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: user.save()
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: force_update=force_update, update_fields=update_fields)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 654, in _save_table
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 687, in _do_insert
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: using=using, raw=raw)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 232, in _insert
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return insert_query(self.model, objs, fields, **kwargs)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1514, in insert_query
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return query.get_compiler(using=using).execute_sql(return_id)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: cursor.execute(sql, params)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return self.cursor.execute(sql, params)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: six.reraise(dj_exc_type, dj_exc_value, traceback)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: return self.cursor.execute(sql, params)
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: IntegrityError: null value in column "email" violates not-null constraint
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: DETAIL:  Failing row contains (20, pbkdf2_sha256$12000$eYZaT8oxsjzq$KeXMoP74Xzjd007j6T+t9aVWkeNv3HY..., 2015-03-04 15:33:44.850018+00, f, demouser, , , null, f, t, 2015-03-04 15:33:44.850018+00).
Mar 04 15:33:44 ip-10-21-1-205.eu-central-1.compute.internal sh[2355]: 10.21.2.156 "POST /v1/auth/register/ HTTP/1.0" 500 27 "curl/7.37.1"
```

**Comment by daemonza** [comment]
Ok think I found the issue. The email parameter is not optional as it says in the documentation.

Running 

```
curl -i -X POST \
       -H "Content-Type: application/json" \
       -d '{"username":"demo11","password":"123","email":"test@example.com"}' \
       http://DEIS/v1/auth/register
```

Works and returns : 

```
{"email":"test@example.com","username":"demo11","first_name":"","last_name":"","is_superuser":false,"is_staff":false,"groups":[],"user_permissions":[],"last_login":"2015-03-04T15:54:04.234368Z","date_joined":"2015-03-04T15:54:04.234368Z","is_active":true}
```

**Comment by bacongobbler** [comment]
Nice snooping. The email is mandatory, so we should fix up the docs on this one.
