### ISSUE TITLE
database silently failing, killing controller

### ISSUE THREAD

**Issue by gvilarino** [deis/deis#3268]
Hi everyone. I discovered this issue a couple of days ago while not being able to register a new user with `deis register`. @gabrtv lent me a hand and we saw that `controller` was reporting:

```
-- Logs begin at Sat 2015-03-07 01:09:39 UTC. --
Mar 11 05:49:13 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:13Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:18 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:18Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:23 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:23Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:28 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:28Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:33 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:33Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:38 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:38Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:43 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:43Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:48 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:48Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:53 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:53Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:49:58 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:49:58Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:03 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:03Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:08 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:08Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:13 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:13Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:18 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:18Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:23 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:23Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:28 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:28Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:33 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:33Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:38 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:38Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:43 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:43Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:48 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:48Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:54 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:54Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:50:59 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:50:59Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:51:04 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:51:04Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:51:09 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:51:09Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:51:14 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:51:14Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:51:19 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:51:19Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
Mar 11 05:51:24 dos-deis-coreos-4 sh[48192]: 2015-03-11T05:51:24Z 08c3e83b2fff confd[256]: ERROR Config check failed: exit status 1
```

We checked `database` and it stated, over and over again:

```
Mar 11 05:51:11 dos-deis-coreos-0 sh[52733]: HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
Mar 11 05:51:11 dos-deis-coreos-0 sh[52733]: STRUCTURED: time=2015-03-11T05:51:11.955218-00 pid=33157
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: wal_e.retries WARNING  MSG: retrying after encountering exception
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: DETAIL: Exception information dump:
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: Traceback (most recent call last):
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/wal_e/retries.py", line 62, in shim
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: return f(*args, **kwargs)
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: bucket.delete_keys([key.name for key in page])
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 726, in delete_keys
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: while delete_keys2(headers):
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 714, in delete_keys2
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: data=data)
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: retry_handler=retry_handler
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1070, in make_request
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: retry_handler=retry_handler)
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1029, in _mexe
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: raise ex
Mar 11 05:52:28 dos-deis-coreos-0 sh[52733]: timeout: timed out
```

After restarting both components the bug went away, but I'm seeing this happen every day now. Can anyone help me find a permanent solution?

Running on Azure, 5-box cluster, deis 1.4.1.

[Here are my `/opt/bin/deis-debug-logs`](https://gist.github.com/gvilarino/43d6e089460f3371109f)

**Comment by carmstrong** [comment]
Is `deis-store-gateway` healthy? What do its logs look like? I wonder if #3183 will help with this...

**Comment by gvilarino** [comment]
I dunno. How do I check it?

**Comment by gvilarino** [comment]
Oh, sorry. I did `ceph -s` and it's ok

**Comment by carmstrong** [comment]
Gateway shouldn't emit many logs, so `deisctl journal store-gateway@1` should show errors if there are any.

I'm wondering if gateway just becomes unresponsive, and that's why database can't write its WAL files anymore.

**Comment by gvilarino** [comment]
Oh, sorry. I did `ceph -s` and it's ok. The thing is I have a cron job to run every hour so my clocks don't go too astray. I'm on Azure and I get 1s+ offsets every couple of hours if not related: #3222

**Comment by gvilarino** [comment]
`deisctl journal store-gateway@1` yields:

```
➜  app git:(development) deisctl journal store-gateway@1
^[f^[f-- Logs begin at Sat 2015-03-07 01:07:32 UTC. --
Mar 07 01:25:32 dos-deis-coreos-0 sh[2424]: curl: (52) Empty reply from server
Mar 07 01:25:33 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:33 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:34 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:34 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:35 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:35 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:36 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:36 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:37 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:37 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:38 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:38 dos-deis-coreos-0 sh[2424]: curl: (52) Empty reply from server
Mar 07 01:25:39 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:39 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:40 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:40 dos-deis-coreos-0 sh[2424]: curl: (52) Empty reply from server
Mar 07 01:25:41 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:41 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:42 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:42 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:43 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:43 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:44 dos-deis-coreos-0 sh[2423]: Starting RADOS gateway...
Mar 07 01:25:44 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:44 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:44 dos-deis-coreos-0 sh[2423]: Starting client.radosgw.gateway...
Mar 07 01:25:44 dos-deis-coreos-0 sh[2423]: 2015-03-07 01:25:44.697775 7f6bc60d8840  0 ceph version 0.87 (c51c8f9d80fa4e0168aa52685b8de40e42758578), process radosgw, pid 930
Mar 07 01:25:44 dos-deis-coreos-0 sh[2423]: /usr/bin/radosgw is running.
Mar 07 01:25:44 dos-deis-coreos-0 sh[2423]: Starting Apache...
Mar 07 01:25:45 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:45 dos-deis-coreos-0 sh[2424]: curl: (56) Recv failure: Connection reset by peer
Mar 07 01:25:46 dos-deis-coreos-0 sh[2423]: deis-store-gateway running...
Mar 07 01:25:46 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:47 dos-deis-coreos-0 sh[2424]: Waiting for ceph gateway on 8888/tcp...
Mar 07 01:25:47 dos-deis-coreos-0 systemd[1]: Started deis-store-gateway.
Mar 08 05:28:12 dos-deis-coreos-0 sh[2423]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 08 05:28:15 dos-deis-coreos-0 sh[2423]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 09 02:42:56 dos-deis-coreos-0 sh[2423]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Mar 09 03:04:18 dos-deis-coreos-0 sh[2423]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

**Comment by gvilarino** [comment]
I'm also seeint that particular last line as the last entry of my (just restarted) `controller`:

```
Mar 11 05:54:55 dos-deis-coreos-4 sh[44385]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

**Comment by carmstrong** [comment]
Yeah, that means etcd is having trouble, which typically points to platform issues :(

**Comment by carmstrong** [comment]
What is `journalctl -fu etcd` on that CoreOS host?

**Comment by gvilarino** [comment]
for host 0:
```
-- Logs begin at Sat 2015-03-07 01:07:32 UTC. --
Mar 11 04:36:46 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 04:36:46.788 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10062 events at index 5147224 completed
Mar 11 04:47:03 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 04:47:03.664 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10008 events at index 5157232 completed
Mar 11 04:57:24 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 04:57:24.656 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10033 events at index 5167265 completed
Mar 11 05:07:41 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:07:41.365 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10003 events at index 5177268 completed
Mar 11 05:18:04 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:18:04.732 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10061 events at index 5187329 completed
Mar 11 05:28:26 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:28:26.970 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10071 events at index 5197400 completed
Mar 11 05:38:46 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:38:46.368 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10027 events at index 5207427 completed
Mar 11 05:49:02 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:49:02.711 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10015 events at index 5217442 completed
Mar 11 05:59:17 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 05:59:17.358 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10015 events at index 5227457 completed
Mar 11 06:09:23 dos-deis-coreos-0 etcd[771]: [etcd] Mar 11 06:09:23.006 INFO      | 08387f2b90d343619ea24e286b31c3c3: snapshot of 10005 events at index 5237462 completed
```

There are two hosts that don't seem to yield a regular log for `journalctl -fu etc`:
```
core@dos-deis-coreos-3 ~ $ journalctl -fu etcd
-- Logs begin at Sat 2015-03-07 01:09:12 UTC. --
Mar 11 05:08:34 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:08:34.063 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10051 events at index 5178132 completed
Mar 11 05:18:55 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:18:55.663 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10007 events at index 5188139 completed
Mar 11 05:28:15 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:28:15.874 INFO      | 47b45a1043144511977bd62c6e1abfd1: warning: heartbeat time out peer="37e821517d374746bd93dda66b7a4320" missed=1 backoff="2s"
Mar 11 05:29:14 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:29:14.333 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10004 events at index 5198143 completed
Mar 11 05:39:32 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:39:32.963 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10095 events at index 5208238 completed
Mar 11 05:49:54 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:49:54.743 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10033 events at index 5218271 completed
Mar 11 05:54:58 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 05:54:58.249 INFO      | 47b45a1043144511977bd62c6e1abfd1: warning: heartbeat time out peer="39b9aef639994faa9d166a1983b36e72" missed=1 backoff="2s"
Mar 11 06:00:04 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 06:00:04.359 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10006 events at index 5228277 completed
Mar 11 06:10:10 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 06:10:10.994 INFO      | 47b45a1043144511977bd62c6e1abfd1: snapshot of 10012 events at index 5238289 completed
Mar 11 06:14:30 dos-deis-coreos-3 etcd[776]: [etcd] Mar 11 06:14:30.480 INFO      | 47b45a1043144511977bd62c6e1abfd1: warning: heartbeat time out peer="37e821517d374746bd93dda66b7a4320" missed=1 backoff="2s"
```

and

```
-- Logs begin at Sat 2015-03-07 01:09:39 UTC. --
Mar 11 05:06:45 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:06:45.991 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10015 events at index 5176347 completed
Mar 11 05:17:06 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:17:06.945 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10017 events at index 5186364 completed
Mar 11 05:27:26 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:27:26.376 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10064 events at index 5196428 completed
Mar 11 05:37:47 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:37:47.090 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10027 events at index 5206455 completed
Mar 11 05:48:03 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:48:03.378 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10052 events at index 5216507 completed
Mar 11 05:54:46 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:54:46.338 INFO      | 39b9aef639994faa9d166a1983b36e72: warning: heartbeat near election timeout: 2.2358992s
Mar 11 05:54:48 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:54:48.036 INFO      | 39b9aef639994faa9d166a1983b36e72: warning: heartbeat near election timeout: 1.6681972s
Mar 11 05:54:57 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:54:57.139 INFO      | 39b9aef639994faa9d166a1983b36e72: warning: heartbeat near election timeout: 3.1268797s
Mar 11 05:58:20 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 05:58:20.744 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10030 events at index 5226537 completed
Mar 11 06:08:28 dos-deis-coreos-4 etcd[778]: [etcd] Mar 11 06:08:28.501 INFO      | 39b9aef639994faa9d166a1983b36e72: snapshot of 10028 events at index 5236565 completed
```

**Comment by gvilarino** [comment]
Also related #3223

**Comment by gvilarino** [comment]
@carmstrong I'm seeing this again just after a few hours of resetting both components. Any leads?

**Comment by gvilarino** [comment]
@carmstrong is this related to #2741 ?

**Comment by carmstrong** [comment]
> Any leads?

Unfortunately this has nothing to do with the components themselves, but rather the underlying platform. Having heartbeat timeouts at 3s is going to cause lots of problems. This sounds like an Azure performance issue, but our provision scripts are doing everything they can to prepare the system for this.

I would raise this issue with Microsoft.

**Comment by gvilarino** [comment]
@carmstrong ok, already sent all my gists and findings to the Microsoft team; thanks

**Comment by carmstrong** [comment]
Closing, as there's nothing actionable we can do here (and I think @gvilarino is on another platform now).
