### ISSUE TITLE
Azure Deployment Script Error: "WindowsAzureMissingResourceError"

### ISSUE THREAD

**Issue by chrisgeo** [deis/deis#3391]
When following the documentation for [using deis with azure](http://docs.deis.io/en/latest/installing_deis/azure/), my instance runs into exceptions being unable to find the service.

There are both storage services with the proper path, and an affinity group setup

The command being run:
```shell
./azure-coreos-cluster foobar-api \
    --subscription <mysubid> \
    --azure-cert ./azure-cert.pem \
    --num-nodes 3 \
    --affinity-group "api" \
    --vm-size large \
    --pip \
    --deis \
    --blob-container-url https://foobar.blob.core.windows.net/vhds/ \
    --data-disk \
    --custom-data azure-user-data
```

It appears to fail attempting to use this PATH:

``` <mysubid>/services/hostedservices/foobar-api/deployments/foobar-api  ```

Below is the output:

```shell
SSH arguments not given, generating certificate
Generated SSH certificate with thumbprint 039AA64E5D940585937906F86AD2C7DBDEC4E501
Creating the hosted service... Successfully created hosted service foobar-api
Uploading SSH certificate... Succeeded in 0s
Creating VM foobar-api-coreos-0... Succeeded in 0s
Creating VM foobar-api-coreos-1... Succeeded in 0s
Creating VM foobar-api-coreos-2... Succeeded in 0s
Traceback (most recent call last):
  File "./azure-coreos-cluster", line 269, in <module>
    ips = get_ips(args.cloud_service_name, args.cloud_service_name)
  File "./azure-coreos-cluster", line 260, in get_ips
    result = sms.get_deployment_by_name(service_name, deployment_name)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 457, in get_deployment_by_name
    Deployment)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 322, in _perform_get
    response = self.perform_get(path, x_ms_version)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 136, in perform_get
    response = self._perform_request(request)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 296, in _perform_request
    return _management_error_handler(ex)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/servicemanagement/__init__.py", line 1996, in _management_error_handler
    return _general_error_handler(http_error)
  File "/foo/g/.virtualenvs/azure/lib/python2.7/site-packages/azure/__init__.py", line 544, in _general_error_handler
    _ERROR_NOT_FOUND.format(str(http_error)))
azure.WindowsAzureMissingResourceError: Not found (Not Found)
```

**Comment by chrisgeo** [comment]
Problem solved: `` --vm-size large ``` is case sensitive.

**Comment by mboersma** [comment]
Wow, I'm glad you figured that out. I'm glad Deis' docs have it correct as `Large`. Thanks for following up.

**Comment by chrisgeo** [comment]
@mboersma It was an interesting problem for something so small. Each vm failed to create itself, but the script kept running overall until it realized the set wasn't being created.

**Comment by munjalpatel** [comment]
I am getting the same error as well. I am issuing the following command:

    ./azure-coreos-cluster deis-dev --subscription 4f2745a4-f317-48a6-a50b-1b8c44ed1d68 --azure-cert azure-cert.free-trial.pem --num-nodes 3 --affinity-group deis-dev --vm-size Large --pip --deis --blob-container-url https://deisdev.blob.core.windows.net/vhds --data-disk --custom-data azure-user-data
    SSH arguments not given, generating certificate
    Generated SSH certificate with thumbprint 7D044D3EF9C388C14FAE6974C9D2CBA48C80D9D3
    Creating the hosted service... Successfully created hosted service deis-dev
    Uploading SSH certificate... . Succeeded in 5s
    Creating VM deis-dev-coreos-0... Succeeded in 0s
    Creating VM deis-dev-coreos-1... Succeeded in 0s
    Creating VM deis-dev-coreos-2... Succeeded in 0s
    Traceback (most recent call last):
      File "./azure-coreos-cluster", line 268, in <module>
        ips = get_ips(args.cloud_service_name, args.cloud_service_name)
      File "./azure-coreos-cluster", line 260, in get_ips
        result = sms.get_deployment_by_name(service_name, deployment_name)
      File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 456, in get_deployment_by_name
    Deployment)
    File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 322, in _perform_get
      response = self.perform_get(path, x_ms_version)
      File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 136, in perform_get
      response = self._perform_request(request)
      File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 296, in _perform_request
      return _management_error_handler(ex)
      File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/__init__.py", line 1996, in _management_error_handler
      return _general_error_handler(http_error)
      File "/usr/local/lib/python2.7/site-packages/azure/__init__.py", line 544, in _general_error_handler
        _ERROR_NOT_FOUND.format(str(http_error)))
    azure.WindowsAzureMissingResourceError: Not found (Not Found)
