### ISSUE TITLE
Not able to install deis on Travis.

### ISSUE THREAD

**Issue by eMxyzptlk** [deis/deis#3668]
I'm getting the following error on Travis:

```
Installing deploy dependencies
!!! Deis support is experimental !!!
pip install --user deis==1.6.0
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting deis==1.6.0
  Downloading deis-1.6.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AcvuUw/deis/setup.py", line 30, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-AcvuUw/deis/setup.py", line 30, in <module>
    
        with open('requirements.txt') as f:
    
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AcvuUw/deis
```

**Comment by mboersma** [comment]
My bad--forgot to add `requirements.txt` to the `MANIFEST.in` file in 574b4d8f911bc5e7a9765c21a1e45264af5862f2.
