### ISSUE TITLE
JSON load failure on "deis apps:run 世界"

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3913]
Many test runs are now failing with a JSON error trying to parse the results of `docker inspect` over SSH:
```python
INFO appssample: test runs 'echo Hello, 世界'
ERROR appssample: appssample_v2.run.1 (run): Expecting object: line 40 column 28 (char 1077)
ERROR Internal Server Error: /v1/apps/appssample/run
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 205, in run
    output_and_rc = app.run(self.request.user, request.data['command'])
  File "/app/api/models.py", line 412, in run
    return c.run(escaped_command)
  File "/app/api/models.py", line 546, in run
    rc, output = self._scheduler.run(job_id, image, entrypoint, command)
  File "/app/scheduler/fleet.py", line 328, in run
    container = json.loads(_output)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 40 column 28 (char 1077)
10.21.1.168 "POST /v1/apps/appssample/run HTTP/1.0" 500 27 "python-requests/2.5.1 CPython/2.7.6 Linux/3.16.0-41-generic"
```
[Here is one example](https://ci.deis.io/job/test-ec2/1461/consoleFull#682192135502066c60b2236c09cc9bf8).

**Comment by mboersma** [comment]
Here is a log with the raw output of what was trying to be decoded:
```
INFO configsample: release configsample-v4 created
INFO configsample: test scaled containers cmd=1
10.21.2.237 "POST /v1/hooks/build HTTP/1.1" 200 79 "deis-builder"
INFO configsample: test runs 'env'
ERROR configsample: configsample_v4.run.1 (run): [{
    "AppArmorProfile": "",
    "Args": [
        "-c",
        "env"
    ],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": false,
        "AttachStdout": true,
        "Cmd": [
            "-c",
            "env"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/bin/bash"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "POWERED_BY=the Deis team",
            "GIT_SHA=ab3e88a6adfbd84324f74981a2c17f137f7efaea",
            "DEIS_APP=configsample",
            "DEIS_RELEASE=v4",
            "BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-go#6eeb09f"
        ],
        "ExposedPorts": {
            "1500/tcp": {}
        },
        "Hostname": "1a7679c7389e",
        "Image": "10.21.2.238:5000/configsample:v4",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,

ERROR Internal Server Error: /v1/apps/configsample/run
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 205, in run
    output_and_rc = app.run(self.request.user, request.data['command'])
  File "/app/api/models.py", line 412, in run
    return c.run(escaped_command)
  File "/app/api/models.py", line 546, in run
    rc, output = self._scheduler.run(job_id, image, entrypoint, command)
  File "/app/scheduler/fleet.py", line 337, in run
    raise ValueError(_output)
ValueError: [{
    "AppArmorProfile": "",
    "Args": [
        "-c",
        "env"
    ],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": false,
        "AttachStdout": true,
        "Cmd": [
            "-c",
            "env"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/bin/bash"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "POWERED_BY=the Deis team",
            "GIT_SHA=ab3e88a6adfbd84324f74981a2c17f137f7efaea",
            "DEIS_APP=configsample",
            "DEIS_RELEASE=v4",
            "BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-go#6eeb09f"
        ],
        "ExposedPorts": {
            "1500/tcp": {}
        },
        "Hostname": "1a7679c7389e",
        "Image": "10.21.2.238:5000/configsample:v4",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,

172.17.42.1 "POST /v1/apps/configsample/run HTTP/1.0" 500 27 "python-requests/2.5.1 CPython/2.7.6 Linux/3.16.0-41-generic"
```

**Comment by carmstrong** [comment]
That certainly looks like a premature exit

**Comment by mboersma** [comment]
Also relevant is possibly #3403, although that did and does seem like it fixed things rather than broke them. :confounded:

**Comment by bacongobbler** [comment]
that was the only relevant change I saw, but I agree that should've fixed things.
