### ISSUE TITLE
deis run throws 500 error

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3932]
Hey,

I am getting a 500 error when running any command via `deis run`. I get this on all apps. All other deis commands are working fine. 

```
deis run ls
```

```
Jun 27 07:37:24 deis-1 sh[12722]: INFO romhut-prod: scott runs 'ls'
Jun 27 07:37:34 deis-1 sh[12722]: ERROR romhut-prod: romhut-prod_v89.run.4 (run): Authentication failed.
Jun 27 07:37:34 deis-1 sh[12722]: ERROR Internal Server Error: /v1/apps/romhut-prod/run
Jun 27 07:37:34 deis-1 sh[12722]: Traceback (most recent call last):
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Jun 27 07:37:34 deis-1 sh[12722]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Jun 27 07:37:34 deis-1 sh[12722]: return view_func(*args, **kwargs)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
Jun 27 07:37:34 deis-1 sh[12722]: return self.dispatch(request, *args, **kwargs)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
Jun 27 07:37:34 deis-1 sh[12722]: response = self.handle_exception(exc)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
Jun 27 07:37:34 deis-1 sh[12722]: response = handler(request, *args, **kwargs)
Jun 27 07:37:34 deis-1 sh[12722]: File "/app/api/views.py", line 171, in run
Jun 27 07:37:34 deis-1 sh[12722]: output_and_rc = app.run(self.request.user, request.data['command'])
Jun 27 07:37:34 deis-1 sh[12722]: File "/app/api/models.py", line 411, in run
Jun 27 07:37:34 deis-1 sh[12722]: return c.run(escaped_command)
Jun 27 07:37:34 deis-1 sh[12722]: File "/app/api/models.py", line 545, in run
Jun 27 07:37:34 deis-1 sh[12722]: rc, output = self._scheduler.run(job_id, image, entrypoint, command)
Jun 27 07:37:34 deis-1 sh[12722]: File "/app/scheduler/fleet.py", line 269, in run
Jun 27 07:37:34 deis-1 sh[12722]: ssh.connect(primaryIP, username="core", pkey=pkey)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 307, in connect
Jun 27 07:37:34 deis-1 sh[12722]: look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
Jun 27 07:37:34 deis-1 sh[12722]: File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 519, in _auth
Jun 27 07:37:34 deis-1 sh[12722]: raise saved_exception
Jun 27 07:37:34 deis-1 sh[12722]: AuthenticationException: Authentication failed.
Jun 27 07:37:35 deis-1 sh[12722]: 10.131.239.90 "POST /v1/apps/romhut-prod/run HTTP/1.0" 500 27 "python-requests/2.5.1 CPython/2.7.5 Darwin/14.3.0"
```

```
Running `ls`...
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
```

**Comment by bacongobbler** [comment]
The authentication failure is pointing out that the key set with `deisctl config platform get sshPrivateKey` cannot be authenticated against the core user on one of the hosts. Is this key the same as the ssh keys on the host?

**Comment by scottrobertson** [comment]
Is this a key generated by deis/coreos to allow it to talk to other hosts? Not one of my own keys? As that doesn't seem to be any of my private keys.

**Comment by scottrobertson** [comment]
Sorted. Again, it's me being an idiot :P. Platform key was set to a super old private key. Sorry for wasting your time @bacongobbler

**Comment by scottrobertson** [comment]
Although, should this not be using the users keys instead? Or is it only the platform admin that can use run?

**Comment by bacongobbler** [comment]
The platform admin should be the only one who knows which key is required to authenticate against the servers. The users shouldn't know that information :)

**Comment by bacongobbler** [comment]
Everyone can use run though (sorry, on phone). They all use this private key, and its not something they need to know.

**Comment by scottrobertson** [comment]
Awesome, thanks @bacongobbler. All sorted now :)
