### ISSUE TITLE
Errors in logs, possibly from store.

### ISSUE THREAD

**Issue by ngerakines** [deis/deis#3969]
I'm seeing a huge number of errors in the logs.

```
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.677722 7fd2a4088700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.698643 7fd2a708e700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.716780 7fcdc54e2700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.737903 7fa2afd7a700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.764561 7f0bfbbeb700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.790842 7fa2ad575700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.806244 7feea7fad700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.813644 7f0bfe3f0700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.841653 7fa2acd74700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.849120 7feea6fab700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.864762 7f0bfb3ea700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.865417 7feea57a8700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.884251 7fa2b057b700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.907858 7fd2a4889700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
Jul 06 12:36:44 deis sh:  2015-07-06 16:36:44.935906 7fd2a508a700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

I saw #3884 but it looks like it was closed. I'm running 1.7.3 in AWS.

**Comment by carmstrong** [comment]
@ngerakines Can you gather some host info? `cat /etc/os-release` and `df -h` are good starters.

**Comment by ngerakines** [comment]
```
core@ip-10-21-2-117 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=633.1.0
VERSION_ID=633.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 633.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@ip-10-21-2-117 ~ $ df -h
Filesystem                                                     Size  Used Avail Use% Mounted on
devtmpfs                                                       3.7G     0  3.7G   0% /dev
tmpfs                                                          3.7G     0  3.7G   0% /dev/shm
tmpfs                                                          3.7G  520K  3.7G   1% /run
tmpfs                                                          3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/xvda9                                                     610G  134G  471G  23% /
/dev/xvda3                                                     985M  334M  601M  36% /usr
tmpfs                                                          3.7G     0  3.7G   0% /media
tmpfs                                                          3.7G     0  3.7G   0% /tmp
/dev/xvda6                                                     108M   60K   99M   1% /usr/share/oem
10.21.2.116,10.21.2.117,10.21.1.250,10.21.1.251,10.21.2.115:/  3.0T  721G  2.3T  24% /var/lib/deis/store
```

**Comment by carmstrong** [comment]
Ok, that all looks fine. Can you check on the Ceph health? http://docs.deis.io/en/latest/troubleshooting_deis/troubleshooting-store/#using-store-admin

I would also try restarting store-gateway: `deisctl restart store-gateway@1`

**Comment by ngerakines** [comment]
```
root@edcb1a359965:/app# ceph -s
    cluster bffa7b76-4dca-482d-b89a-020d0efdd099
     health HEALTH_WARN
            pool .rgw.buckets has too few pgs
     monmap e5: 5 mons at {ip-10-21-1-250.us-west-2.compute.internal=10.21.1.250:6789/0,ip-10-21-1-251.us-west-2.compute.internal=10.21.1.251:6789/0,ip-10-21-2-115.us-west-2.compute.internal=10.21.2.115:6789/0,ip-10-21-2-116.us-west-2.compute.internal=10.21.2.116:6789/0,ip-10-21-2-117.us-west-2.compute.internal=10.21.2.117:6789/0}
            election epoch 680, quorum 0,1,2,3,4 ip-10-21-1-250.us-west-2.compute.internal,ip-10-21-1-251.us-west-2.compute.internal,ip-10-21-2-115.us-west-2.compute.internal,ip-10-21-2-116.us-west-2.compute.internal,ip-10-21-2-117.us-west-2.compute.internal
     mdsmap e206: 1/1/1 up {0=ip-10-21-1-250.us-west-2.compute.internal=up:active}, 4 up:standby
     osdmap e1975: 5 osds: 5 up, 5 in
      pgmap v4113391: 1536 pgs, 12 pools, 54172 MB data, 35279 objects
            697 GB used, 2327 GB / 3048 GB avail
                1536 active+clean
  client io 367 kB/s rd, 143 kB/s wr, 655 op/s
```

**Comment by ngerakines** [comment]
I can restart the store gateway, but `deisctl list` shows that it is "ready".

```
deis-store-gateway@1.service	19cf8d38.../10.21.2.115	loaded	active		running
```

**Comment by bacongobbler** [comment]
your cluster is in a warning state due to too few placement groups. I'd see if some manual intervention via http://ceph.com/docs/master/rados/troubleshooting/troubleshooting-pg/#stuck-placement-groups may help

**Comment by carmstrong** [comment]
> I'd see if some manual intervention via

That's not the right documentation for this - this is due to too few placement groups having been created for the amount of data in that pool. That documentation is for stuck placement groups.

**Comment by carmstrong** [comment]
Ok. I'm not sure where the `rgw_obj_remove()` error is coming from, but we can resolve the `pool .rgw.buckets has too few pgs` warning and see if things are happier. First, get the number of placement groups for your `.rgw.buckets` pool: `ceph osd pool get .rgw.buckets pg_num`. You'll need to increase this by a power of 2. Try small increments until the warning goes away. 

For example, so set the pool to 196 placement groups:

```
ceph osd pool set .rgw.buckets pg_num 196
ceph osd pool set .rgw.buckets pgp_num 196
```

**Comment by ngerakines** [comment]
I upped the count by a power of two and the ceph status is good now.

```
    cluster bffa7b76-4dca-482d-b89a-020d0efdd099
     health HEALTH_OK
     monmap e5: 5 mons at {ip-10-21-1-250.us-west-2.compute.internal=10.21.1.250:6789/0,ip-10-21-1-251.us-west-2.compute.internal=10.21.1.251:6789/0,ip-10-21-2-115.us-west-2.compute.internal=10.21.2.115:6789/0,ip-10-21-2-116.us-west-2.compute.internal=10.21.2.116:6789/0,ip-10-21-2-117.us-west-2.compute.internal=10.21.2.117:6789/0}
            election epoch 680, quorum 0,1,2,3,4 ip-10-21-1-250.us-west-2.compute.internal,ip-10-21-1-251.us-west-2.compute.internal,ip-10-21-2-115.us-west-2.compute.internal,ip-10-21-2-116.us-west-2.compute.internal,ip-10-21-2-117.us-west-2.compute.internal
     mdsmap e206: 1/1/1 up {0=ip-10-21-1-250.us-west-2.compute.internal=up:active}, 4 up:standby
     osdmap e1990: 5 osds: 5 up, 5 in
      pgmap v4114047: 1664 pgs, 12 pools, 54097 MB data, 35816 objects
            689 GB used, 2334 GB / 3048 GB avail
                1664 active+clean
  client io 402 kB/s rd, 156 kB/s wr, 739 op/s
```

Unfortunately, I'm still seeing a lot of log entries:

```
Jul 06 13:10:24 deis sh:  2015-07-06 17:10:24.129612 7f0bfbbeb700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

**Comment by ngerakines** [comment]
I'm also seeing this periodically:

```
Jul 06 13:15:02 deis sh:  wal_e.retries WARNING  MSG: retrying after encountering exception
Jul 06 13:15:02 deis sh:  DETAIL: Exception information dump:
Jul 06 13:15:02 deis sh:  Traceback (most recent call last):
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/wal_e/retries.py", line 62, in shim
Jul 06 13:15:02 deis sh:  return f(*args, **kwargs)
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/wal_e/worker/s3/s3_deleter.py", line 27, in _delete_batch
Jul 06 13:15:02 deis sh:  bucket.delete_keys([key.name for key in page])
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 726, in delete_keys
Jul 06 13:15:02 deis sh:  while delete_keys2(headers):
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 714, in delete_keys2
Jul 06 13:15:02 deis sh:  data=data)
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
Jul 06 13:15:02 deis sh:  retry_handler=retry_handler
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
Jul 06 13:15:02 deis sh:  retry_handler=retry_handler)
Jul 06 13:15:02 deis sh:  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
Jul 06 13:15:02 deis sh:  raise ex
```

**Comment by carmstrong** [comment]
> I'm also seeing this often:

@aledbf mentioned that the `rgw_obj_remove()` error was caused by a temporary file that wasn't removed. The debugging line that we'd like to see is https://github.com/ceph/ceph/blob/master/src/cls/rgw/cls_rgw.cc#L1944, and to do that we need to bump the log level for gateway to 20.. See http://ceph.com/docs/master/rados/troubleshooting/log-and-debug/#subsystem-log-and-debug-settings for details. Unfortunately, off the top of my head I'm not sure which `ceph tell` command we want to use. If you're feeling up to it, maybe the Ceph mailing list or IRC channel would be able to help: https://ceph.com/resources/mailing-list-irc/

So sorry you're running into this - I don't understand the conditions that lead to this :/

**Comment by ngerakines** [comment]
> So sorry you're running into this - I don't understand the conditions that lead to this :/

I'm sure it has to do with a recent failure we experienced. Last week or so, during an application deploy the build timed out and two versions of the application ended up being deployed. Immediately after that, we started seeing deis internal application failures and the cluster became unresponsive. Eventually I got everything shutdown and off (read as: production site downtime) I attempted to bring the cluster back up. Unfortunately when it came back up, all of our applications (including their configuration was missing).

I ended up upgrading the cluster to 1.7.3 (from 1.6.0) while everything was down redeployed our production applications.

**Comment by carmstrong** [comment]
Wow... sounds like quite the failure :/ Could you open an issue to track the situation that led to two version of the app being deployed? Sounds like a locking mechanism that should prevent that from happening wasn't working.

**Comment by aledbf** [comment]
@ngerakines you can force a [deep scrub](http://ceph.com/docs/master/rados/configuration/osd-config-ref/#scrubbing) of the ceph content to verify the content:
Follow [using-store-admin](http://docs.deis.io/en/latest/troubleshooting_deis/troubleshooting-store/#using-store-admin) to get a shell and be able to execute:
```
ceph pg dump | grep -i active | cut -f 1 | while read i; do ceph pg deep-scrub ${i}; done
```

when this ends execute:
```
ceph -w
```

to check the progress. Once it ends restart the `deis-store-gateway` component.

**Comment by mboersma** [comment]
@ngerakines did you get anywhere with solving this? And if you can reproduce the specific conditions with two versions of the app being deployed, please open that as a separate issue. Thanks!

**Comment by ineu** [comment]
Hi guys. I'm also experiencing this problem, though I run CoreOS unlike #3884 and my Ceph is healthy unlike this topic. I've never seen such errors when was running cluster with every upgrade from 1.5 to 1.8. They appeared after I've reinstalled CoreOS and Deis from scratch, now I see them on each of three machines. 
All `cls_cxx_remove` errors come from deis-store-daemons

**Comment by matiasdecarli** [comment]
Im running into this aswell. Running on Azure with a 5 machine cluster. The ceph looks healthy, but Im still getting the `rgw_obj_remove()`

**Comment by gvilarino** [comment]
(working with @matiasdecarli in this same cluster and issue)

@aledbf : I followed your instructions (`deep scrub` all, wait for `ceph -w` to normalize, stopping and restarting the gateway) and we are still getting:

```
deis-store-daemon[1]: 2015-09-01 19:09:51.213697 7fe2df9dd700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
deis-store-daemon[1]: 2015-09-01 19:09:51.506990 7fe2df9dd700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
deis-store-daemon[1]: 2015-09-01 19:09:52.873456 7fe2e01de700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

Aditionally, I'm seeing a this kig every once in a while:

```
deis-store-monitor[1]: 2015-09-01 19:09:53.942190 7f00e1134700  0 mon.murallydeis02-coreos-2@2(peon).data_health(288) update_stats avail 83%!t(MISSING)otal 95865 MB, used 10653 MB, avail 80075 MB
```

Any ideas on how to proceed here?

The only thing big changes we've made on the cluster since we first deployed are:

1. Added a `NewRelic` monitoring service
2. Added a `DataDog` monitoring service (which, incidentally, stopped working after 3 days of working properly and is no longer being able to start)
3. Added an affinity query string to the router (as per #3088) so we can guarantee the handshake queries for websocket handshake all hit the same node (it's discarded after that)

We started monitoring the logs today and this error was the first thing we saw. Any ideas?

Thanks in advance.

**Comment by gvilarino** [comment]
I already did `deisctl restart store-daemon` and the first log I see after it complets the restart is:

```
<cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

:disappointed:

**Comment by carmstrong** [comment]
@gvilarino Unfortunately, this has been reported a handful of times in the past, but we've never been able to get to the bottom of it. :(

**Comment by gvilarino** [comment]
@carmstrong dang! Here's the initial log of `store-daemon`. Maybe it helps?

```
core@murallydeis02-coreos-0 ~ $ docker logs deis-store-daemon
store-daemon: starting daemon on murallydeis02-coreos-0...
2015-09-01 19:53:30.641211 7fa40aa55900  0 ceph version 0.94.2 (5fb85614ca8f354284c713a2f9c610860720bbf3), process ceph-osd, pid 1
starting osd.3 at :/0 osd_data /var/lib/ceph/osd/ceph-3 /var/lib/ceph/osd/ceph-3/journal
2015-09-01 19:53:32.425350 7fa40aa55900  0 filestore(/var/lib/ceph/osd/ceph-3) backend generic (magic 0xef53)
2015-09-01 19:53:32.457339 7fa40aa55900  0 genericfilestorebackend(/var/lib/ceph/osd/ceph-3) detect_features: FIEMAP ioctl is supported and appears to work
2015-09-01 19:53:32.457367 7fa40aa55900  0 genericfilestorebackend(/var/lib/ceph/osd/ceph-3) detect_features: FIEMAP ioctl is disabled via 'filestore fiemap' config option
2015-09-01 19:53:33.438496 7fa40aa55900  0 genericfilestorebackend(/var/lib/ceph/osd/ceph-3) detect_features: syncfs(2) syscall fully supported (by glibc and kernel)
2015-09-01 19:53:33.539419 7fa40aa55900  0 filestore(/var/lib/ceph/osd/ceph-3) limited size xattrs
2015-09-01 19:53:34.280262 7fa40aa55900  0 filestore(/var/lib/ceph/osd/ceph-3) mount: enabling WRITEAHEAD journal mode: checkpoint is not enabled
2015-09-01 19:53:38.981663 7fa40aa55900 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
2015-09-01 19:53:38.981693 7fa40aa55900  1 journal _open /var/lib/ceph/osd/ceph-3/journal fd 18: 5368709120 bytes, block size 4096 bytes, directio = 1, aio = 0
2015-09-01 19:53:39.989249 7fa40aa55900  1 journal _open /var/lib/ceph/osd/ceph-3/journal fd 18: 5368709120 bytes, block size 4096 bytes, directio = 1, aio = 0
2015-09-01 19:53:40.052833 7fa40aa55900  0 <cls> cls/hello/cls_hello.cc:271: loading cls_hello
2015-09-01 19:53:40.413233 7fa40aa55900  0 osd.3 69 crush map has features 1107558400, adjusting msgr requires for clients
2015-09-01 19:53:40.413266 7fa40aa55900  0 osd.3 69 crush map has features 1107558400 was 8705, adjusting msgr requires for mons
2015-09-01 19:53:40.413273 7fa40aa55900  0 osd.3 69 crush map has features 1107558400, adjusting msgr requires for osds
2015-09-01 19:53:40.413286 7fa40aa55900  0 osd.3 69 load_pgs
2015-09-01 19:53:42.036291 7fa40aa55900  0 osd.3 69 load_pgs opened 441 pgs
2015-09-01 19:53:42.142893 7fa40aa55900 -1 osd.3 69 log_to_monitors {default=true}
2015-09-01 19:53:42.227825 7fa3f7ebf700  0 osd.3 69 ignoring osdmap until we have initialized
2015-09-01 19:53:42.228127 7fa3f7ebf700  0 osd.3 69 ignoring osdmap until we have initialized
2015-09-01 19:53:42.309531 7fa3e4395700  0 -- 10.0.0.4:6807/1 >> 10.0.0.5:6801/1 pipe(0xaa58000 sd=26 :0 s=1 pgs=0 cs=0 l=0 c=0x55fbfa0).fault with nothing to send, going to standby
2015-09-01 19:53:42.310608 7fa3e4496700  0 cephx: verify_reply couldn't decrypt with error: error decoding block for decryption
2015-09-01 19:53:42.310645 7fa3e4496700  0 -- 10.0.0.4:6807/1 >> 10.0.0.6:6801/1 pipe(0xaa1f000 sd=25 :47925 s=1 pgs=0 cs=0 l=0 c=0x55fbe40).failed verifying authorize reply
2015-09-01 19:53:42.310692 7fa3e4496700  0 -- 10.0.0.4:6807/1 >> 10.0.0.6:6801/1 pipe(0xaa1f000 sd=25 :47925 s=1 pgs=0 cs=0 l=0 c=0x55fbe40).fault with nothing to send, going to standby
2015-09-01 19:53:42.543685 7fa40aa55900  0 osd.3 69 done with init, starting boot process
2015-09-01 19:53:47.989960 7fa3e3891700  0 -- 10.0.0.4:6807/1 >> 10.0.0.7:6802/1 pipe(0xaa1f000 sd=160 :6807 s=0 pgs=0 cs=0 l=0 c=0x55fc680).accept connect_seq 0 vs existing 0 state connecting
2015-09-01 19:53:49.159913 7fa3e126b700  0 -- 10.0.0.4:6806/1 >> 10.0.0.5:0/2968240034 pipe(0xad8b000 sd=68 :6806 s=0 pgs=0 cs=0 l=0 c=0xb199c80).accept peer addr is really 10.0.0.5:0/2968240034 (socket is 10.0.0.5:50953/0)
2015-09-01 19:53:50.753018 7fa3edeab700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
2015-09-01 19:53:50.766024 7fa3edeab700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

**Comment by carmstrong** [comment]
@gvilarino I *think* this is specific to the gateway component - it has data mapped that it no longer thinks exists. See the thread here when I previously had asked for help from the Ceph community: http://lists.ceph.com/pipermail/ceph-users-ceph.com/2015-July/002925.html

**Comment by gvilarino** [comment]
We've been trying different stuff (thanks @aledbf !) but haven't been able to make that log go away. After stopping all `store` services, forcing an `ntpdate` in all hosts and then restarting everything, `ceph` started reporting `HEALTH_WARN` in some nodes and we saw some other errors.

After killing the cluster and creating a new one, we'got some other errors when launching `platform` and after it went through we also got `HEALTH_WARN` on ceph due to clock skews.

It seems that `Azure` support is still not prod-ready :(

**Comment by carmstrong** [comment]
> It seems that Azure support is still not prod-ready :(

:( If we can try to identify root issues, we can pass feedback to our friends at Microsoft who have been helping us get CoreOS and Deis running on Azure. But I understand that's not going to alleviate immediate issues/concerns that are blocking...

**Comment by gvilarino** [comment]
Is there anything we can provide to help find those issues? The clusters are killed now but there's a whole log dump filled with that stuff. Not sure if it will help, tho

**Comment by gvilarino** [comment]
Just created a new cluster on Azure. *Right after* finishing the `platform start` I hop into host 1 and...

```
root@deismuralcluster-coreos-0:/# ceph -s
    cluster 6f7d7ad8-cd55-4e0a-8268-562e3fc39026
     health HEALTH_WARN
            clock skew detected on mon.deismuralcluster-coreos-1, mon.deismuralcluster-coreos-2, mon.deismuralcluster-coreos-3, mon.deismuralcluster-coreos-4
     monmap e5: 5 mons at {deismuralcluster-coreos-0=10.0.0.4:6789/0,deismuralcluster-coreos-1=10.0.0.5:6789/0,deismuralcluster-coreos-2=10.0.0.6:6789/0,deismuralcluster-coreos-3=10.0.0.7:6789/0,deismuralcluster-coreos-4=10.0.0.8:6789/0}
            election epoch 10, quorum 0,1,2,3,4 deismuralcluster-coreos-0,deismuralcluster-coreos-1,deismuralcluster-coreos-2,deismuralcluster-coreos-3,deismuralcluster-coreos-4
     mdsmap e8: 1/1/1 up {0=deismuralcluster-coreos-0=up:active}, 4 up:standby
     osdmap e43: 16 osds: 5 up, 5 in
      pgmap v345: 768 pgs, 12 pools, 471 MB data, 362 objects
            32626 MB used, 411 GB / 468 GB avail
                 768 active+clean
  client io 204 B/s rd, 2047 B/s wr, 0 op/s
root@deismuralcluster-coreos-0:/# ceph -w
    cluster 6f7d7ad8-cd55-4e0a-8268-562e3fc39026
     health HEALTH_WARN
            clock skew detected on mon.deismuralcluster-coreos-1, mon.deismuralcluster-coreos-2, mon.deismuralcluster-coreos-3, mon.deismuralcluster-coreos-4
     monmap e5: 5 mons at {deismuralcluster-coreos-0=10.0.0.4:6789/0,deismuralcluster-coreos-1=10.0.0.5:6789/0,deismuralcluster-coreos-2=10.0.0.6:6789/0,deismuralcluster-coreos-3=10.0.0.7:6789/0,deismuralcluster-coreos-4=10.0.0.8:6789/0}
            election epoch 10, quorum 0,1,2,3,4 deismuralcluster-coreos-0,deismuralcluster-coreos-1,deismuralcluster-coreos-2,deismuralcluster-coreos-3,deismuralcluster-coreos-4
     mdsmap e8: 1/1/1 up {0=deismuralcluster-coreos-0=up:active}, 4 up:standby
     osdmap e43: 16 osds: 5 up, 5 in
      pgmap v347: 768 pgs, 12 pools, 471 MB data, 362 objects
            32626 MB used, 411 GB / 468 GB avail
                 768 active+clean
  client io 270 B/s rd, 450 B/s wr, 0 op/s

2015-09-02 21:03:17.820843 mon.0 [INF] pgmap v347: 768 pgs: 768 active+clean; 471 MB data, 32626 MB used, 411 GB / 468 GB avail; 270 B/s rd, 450 B/s wr, 0 op/s
2015-09-02 21:03:31.306543 mon.0 [INF] pgmap v348: 768 pgs: 768 active+clean; 471 MB data, 32612 MB used, 411 GB / 468 GB avail; 204 B/s rd, 273 B/s wr, 0 op/s
2015-09-02 21:03:32.526890 mon.0 [INF] pgmap v349: 768 pgs: 768 activ
```

**Comment by gvilarino** [comment]
Also, I tried this last time with a storage account using the `Locally Redundant Store` setting for the storage account; reported to be [better performing](http://blogs.msdn.com/b/windowsazurestorage/archive/2013/12/04/introducing-read-access-geo-replicated-storage-ra-grs-for-windows-azure-storage.aspx) than `Geo-Redundant` the default). But still clock skew :(

**Comment by jannispl** [comment]
@carmstrong I just came across this on a 3-node bare metal cluster. HEALTH_OK, did a deep scrub on all PGs, restarted store-daemon and store-gateway, nothing helped.

**Comment by bladedoyle** [comment]
In my case the "cephx: verify_reply couldn't decrypt with error: error decoding block for decryption" errors were due to having iptables blocking the ceph ports.  I resolve it with these rules:

-A INPUT -m tcp -p tcp --dport 6789 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 6800:6810 -j ACCEPT

**Comment by bacongobbler** [comment]
@gvilarino thank you for the logs, but I didn't see anything obvious come from it. Judging from the rest of the comments I still don't see a way to reliably reproduce this problem. Does anyone know how we can re-create this problem or has anyone diagnosed why this would occur?

Since this isn't necessarily a new feature, we could punt on this until after the LTS release once we get a fix out for this. LTS is mostly there to implement any new features, after which v1 will be on life support to fix up issues like this one.

**Comment by gvilarino** [comment]
I really don't know how to repro, sorry :(

**Comment by bacongobbler** [comment]
closing as inactive and irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
