### ISSUE TITLE
Running docker registry results in out of disk  space error

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4022]
the docker registry /tmp directory seems to be a bit small for what it needs...
any idea how to increase this? I ran make dev-registry as pre instructions...

```
[nathan@zeta deis]$ docker exec 31ea4aab2a0d df -h
Filesystem                                                                                         Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:2-2371693-31ea4aab2a0d237d4ced88622428bc51b8a865f6539a3cebb5140f6740a62fa2  9.8G  447M  8.8G   5% /
tmpfs                                                                                               16G     0   16G   0% /dev
shm                                                                                                 64M     0   64M   0% /dev/shm
tmpfs                                                                                               64M   12K   64M   1% /run
tmpfs                                                                                               64M   64M     0 100% /tmp
/dev/mapper/luks-f616d7de-54b4-45bf-9bf0-d9495d07afb1                                               45G  9.2G   33G  22% /etc/hosts
tmpfs                                                                                               16G     0   16G   0% /proc/kcore
[nathan@zeta deis]$ docker exec 31ea4aab2a0d ls /tmp
docker-registry.db
registry
[nathan@zeta deis]$ docker exec 31ea4aab2a0d ls -l /tmp
total 4
-rw-r--r--. 1 root root 4096 Jul 14 01:20 docker-registry.db
drwxr-xr-x. 4 root root   80 Jul 14 01:17 registry
[nathan@zeta deis]$ 
[nathan@zeta deis]$ docker exec 31ea4aab2a0d du -h /tmp
16M	/tmp/registry/images/fe4f368d0c4620929067e25e05ca3bf82d96d01d27c2c06b622bd93b45eeb76c
16K	/tmp/registry/images/0aa379bbe6b4037e6ff199c4d7e819a283644e0bae9b180c6b36a1e10f29b9b7
16K	/tmp/registry/images/68de2f7dd26b5068ff86f4a6d5efb7559a419867d1d0ea4873460610ce924ed5
16K	/tmp/registry/images/180ec7952fe6c5f26f8332638850635e0a94392eadf79a1c23ffede78a25eda6
16K	/tmp/registry/images/9f9c7f1798f063c9e9c1302a521a3190ba765a8037c748f39027754eba252d45
16K	/tmp/registry/images/07ab49c6d303b5310759477527fb812f8c7d2d797a5dc217bcae245e8083b6e7
2.6M	/tmp/registry/images/6f9fa8c043a808c615300377efd14f6c9df88152650bf050c91ce1f411143144
2.1M	/tmp/registry/images/1dbcb5b28d79d3afaf95c6d36c4087ef7e31a0a6b85a4192be0962f76e97206a
2.0M	/tmp/registry/images/a1eca2d2be629eac061cf643be9b33f6cb4b5ee436e11086bf0d316b1f4f82ae
16K	/tmp/registry/images/50f509705de514d25e2d57dae2dd86029a0db3712692ed5e057243a950856bb5
16K	/tmp/registry/images/61bc2bda2c58051db23ed531cca82caef50f9ef02d15a9d6c5fffa35b03340b5
16K	/tmp/registry/images/0071823b030170efbd88daf5805e3cbcb8ff408b2a8776e62c66db4ccc316db6
16K	/tmp/registry/images/416d8030f69b2480177a63b0679a2e10227c6318f251f33a082072c0fdadf2e1
16K	/tmp/registry/images/26fe8fcacf50a449db5bf497731aa6355d50f54fe9a47b41dcd09f2364796e3b
1.4M	/tmp/registry/images/b0076a076a36ef4cb1fc36363cf55e9923e4434e2713976d73976b569d6b667c
440K	/tmp/registry/images/6a38529ec16d9a40848a6923bbedd6a35ae528ce6a3e65db894ab1c0ab6ccccd
16K	/tmp/registry/images/2aaf6d545b03b2f5da97dc0c256d8d75b55b8154957e112e7ffd8148f7229c80
6.4M	/tmp/registry/images/d7b83c494a4258cf1d28500f33a9bfc43ec34dd4d49c1bc41e6335a3040f4141
16K	/tmp/registry/images/811c5758053dc3f22c42d87482383b9ea691eff9003f174f18993c7f023772f7
6.4M	/tmp/registry/images/c1aaa1c1fbf1ca72f163c4b5225a54a48e3a2b983befefa8481e399e2b871b74
16K	/tmp/registry/images/98603ddc98593fb878b7a37951868dc5b62f4749ea0650a08455de005b704e6c
16K	/tmp/registry/images/ad8549617a543ce1fe22f15218852807de93967c29bcedd30ac070c8181298a1
16K	/tmp/registry/images/e942a07a925c94c7e7d678384d36bfe42aa5e482e21309d9facd4b919f155010
16K	/tmp/registry/images/15e7c9509e8ebb120052d96bbac84e8780d9c7f966520d5fa415895f50b7c8a3
16K	/tmp/registry/images/0a87074877a36314971ef70c5ddd2a001d7746f0a37d6da38ccc64ff9035b53f
16K	/tmp/registry/images/be5583def6320b84548cbcff590e5b3301c79b23c30942d4199e049093736cda
16K	/tmp/registry/images/539286fbd9d111a4db84a5f42b4b1e0b11ede4b7261bdb7620f46b62f1911146
16K	/tmp/registry/images/a443a9ce8a570a44baa63b37d3526739e16f1692cfdafb181bc3ce53c9a70d21
16K	/tmp/registry/images/ef6e079741faf37a70e2e0fe16caa3c2ade182179346919fb06e329c704624c1
16K	/tmp/registry/images/55c571cfb29de04557e1dd894eeb4e7509b84d637cbe627ea2132a446848cbb4
16K	/tmp/registry/images/bf910081a84bc95d5b662a5a4f518ba131df5f9a93b4ad57cd6dbd2463368080
16K	/tmp/registry/images/b2c8f12b75a37fe3614e8a379f64fde13996172f2acae35571cc3938babb74af
16K	/tmp/registry/images/ceafca2a66cda729099f725d616c718d3c2608cf7033f3cb88b590dd7d391101
16K	/tmp/registry/images/020d18c1fa75fd891067b86abed43bf2ac91bc2d4bd852e7ea5cf089674d31fa
16K	/tmp/registry/images/07c0b1ade2973f1eba2c6d1003893fa104a1d0475678e5b7cd9b160315d89768
4.4M	/tmp/registry/images/d8c3e5c507a5d7871a9bff80e91dbf0367935efda83990bbf3637b7048fc1d06
14M	/tmp/registry/images/20e2111b6732897471df69c9fb9c43f6f85efdc8f3535865d540d72c59d0aa5a
2.6M	/tmp/registry/images/89133dcd53c717b5b73384869759ace46956b845954b8fc9d2ce14e93aa2f2e5
2.1M	/tmp/registry/images/f1aaf43580707080da010d6e054788feb1dfd4cd11620d75b61e01c7155e4b9d
2.0M	/tmp/registry/images/3948227a2c3a6835722b64b0683ae70071f80467ed6deecc812bff8f019f95fc
2.2M	/tmp/registry/images/878b6301bedafae11e013d8393be8bb3919d06e06917007991933b59c040c7fe
64M	/tmp/registry/images
4.0K	/tmp/registry/repositories/deis/controller
12K	/tmp/registry/repositories/deis/cache
12K	/tmp/registry/repositories/deis/builder
28K	/tmp/registry/repositories/deis
28K	/tmp/registry/repositories
64M	/tmp/registry
64M	/tmp




14/Jul/2015:01:20:31 +0000 ERROR: Exception on /v1/images/fe4f368d0c4620929067e25e05ca3bf82d96d01d27c2c06b622bd93b45eeb76c/layer [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 280, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 226, in put_image_layer
    save_checksums(image_id, csums)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/images.py", line 316, in save_checksums
    store.put_content(checksum_path, json.dumps(checksums))
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/drivers/file.py", line 63, in put_content
    f.write(content)
IOError: [Errno 28] No space left on device
```

**Comment by bacongobbler** [comment]
`make dev-registry` just [wraps docker run](https://github.com/deis/deis/blob/master/Makefile#L20). I'm not quite sure how this would occur, unfortunately. Looks like https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/ might be a fun exercise, but I'd imagine you'd get a better response from docker/docker about this issue. :)

**Comment by carmstrong** [comment]
@nathansamson I'd also look at `df -h` on your Docker host.

**Comment by mboersma** [comment]
I don't think this is within Deis' scope to fix--the local dev registry container may fill up if used for a long time.
