### ISSUE TITLE
deis-controller fails with CannotSendRequest

### ISSUE THREAD

**Issue by ineu** [deis/deis#4209]
After one of three machines rebooted (bare metal), deis-controller no longer works. I've tried to restart it and rebooted two remaining machines, didn't help. When I try to do `deis ps`, I see following in controller logs:

```
Aug 04 21:02:26 apps-3.example.com sh[14785]: ERROR Internal Server Error: /v1/apps/engine-new/containers
Aug 04 21:02:26 apps-3.example.com sh[14785]: Traceback (most recent call last):
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Aug 04 21:02:26 apps-3.example.com sh[14785]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Aug 04 21:02:26 apps-3.example.com sh[14785]: return view_func(*args, **kwargs)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
Aug 04 21:02:26 apps-3.example.com sh[14785]: return self.dispatch(request, *args, **kwargs)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
Aug 04 21:02:26 apps-3.example.com sh[14785]: response = self.handle_exception(exc)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
Aug 04 21:02:26 apps-3.example.com sh[14785]: response = handler(request, *args, **kwargs)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 46, in list
Aug 04 21:02:26 apps-3.example.com sh[14785]: return Response(serializer.data)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 463, in data
Aug 04 21:02:26 apps-3.example.com sh[14785]: ret = super(Serializer, self).data
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 212, in data
Aug 04 21:02:26 apps-3.example.com sh[14785]: self._data = self.to_representation(self.instance)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in to_representation
Aug 04 21:02:26 apps-3.example.com sh[14785]: ret[field.field_name] = field.to_representation(attribute)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 565, in to_representation
Aug 04 21:02:26 apps-3.example.com sh[14785]: self.child.to_representation(item) for item in iterable
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 423, in to_representation
Aug 04 21:02:26 apps-3.example.com sh[14785]: attribute = field.get_attribute(instance)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 290, in get_attribute
Aug 04 21:02:26 apps-3.example.com sh[14785]: return get_attribute(instance, self.source_attrs)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 70, in get_attribute
Aug 04 21:02:26 apps-3.example.com sh[14785]: instance = getattr(instance, attr)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/app/api/models.py", line 432, in state
Aug 04 21:02:26 apps-3.example.com sh[14785]: return self._scheduler.state(self._job_id).name
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/app/scheduler/fleet.py", line 351, in state
Aug 04 21:02:26 apps-3.example.com sh[14785]: self._get_unit(name)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/app/scheduler/fleet.py", line 56, in _get_unit
Aug 04 21:02:26 apps-3.example.com sh[14785]: resp = self._request_unit('GET', name)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/app/scheduler/fleet.py", line 50, in _request_unit
Aug 04 21:02:26 apps-3.example.com sh[14785]: headers=headers, body=json.dumps(body))
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/httplib.py", line 1001, in request
Aug 04 21:02:26 apps-3.example.com sh[14785]: self._send_request(method, url, body, headers)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/httplib.py", line 1029, in _send_request
Aug 04 21:02:26 apps-3.example.com sh[14785]: self.putrequest(method, url, **skips)
Aug 04 21:02:26 apps-3.example.com sh[14785]: File "/usr/lib/python2.7/httplib.py", line 892, in putrequest
Aug 04 21:02:26 apps-3.example.com sh[14785]: raise CannotSendRequest()
Aug 04 21:02:26 apps-3.example.com sh[14785]: CannotSendRequest
```

The message is cryptic and I don't understand what to look at. Ceph is ok, fleet sees all machines, etcd is fine.

**Comment by ineu** [comment]
Ok, I found it. `/var/run/fleet.sock` on the host system was a directory. Looks like it wasn't existing when container was started, so docker created a directory.

This looks like a bug. `deis-controller` service file should check if sockets are available before trying to run ExecStart.

**Comment by mboersma** [comment]
> deis-controller service file should check if sockets are available before trying to run ExecStart

That sounds likely. Thanks for debugging this @ineu!

**Comment by carmstrong** [comment]
I think the fix here is to update the `deis-controller.service` unit to require the fleet socket. It should describe the actual dependency that we have - thanks @ineu!

The change should be here: https://github.com/deis/deis/blob/master/deisctl/units/deis-controller.service#L1-L4

**Comment by ineu** [comment]
Great, thanks guys!
