### ISSUE TITLE
Issue removing ssl cert from application with spaces in common name

### ISSUE THREAD

**Issue by msull92** [deis/deis#4487]
I am having an issue removing an ssl certificate from an application where the certificate's common name has spaces in it. Is there a way to manually remove this using etcdctl?

**Comment by benwilber** [comment]
@msull92 can you try replacing the spaces with `%20`

**Comment by msull92** [comment]
I would love to do that, but it's not even showing up in etcdctl, see below:

![screenshot 2015-09-16 09 56 06](https://cloud.githubusercontent.com/assets/513720/9908438/3f38ed1c-5c59-11e5-9f34-8891c74638cc.png)

Yet it still shows up with the client call.
![screenshot 2015-09-16 09 55 21](https://cloud.githubusercontent.com/assets/513720/9908442/43efd1f4-5c59-11e5-9416-6ee6889004ea.png)

**Comment by msull92** [comment]
@benwilber forgot to tag you

**Comment by carmstrong** [comment]
@msull92 It looks like the certificate has been cleared from etcd (and thus shouldn't be served any longer by the router), but is still there in our database.

Do you see an error when you try to delete it? If you could also paste the logs from the controller component when you try to delete the certificate, that'd be helpful. Thanks!

**Comment by msull92** [comment]
@carmstrong 

This causes the log below.
![screenshot 2015-09-16 10 42 02](https://cloud.githubusercontent.com/assets/513720/9909851/afa4895c-5c5f-11e5-9e4f-3bcf90e112b9.png)

![screenshot 2015-09-16 10 42 25](https://cloud.githubusercontent.com/assets/513720/9909845/ab08d506-5c5f-11e5-8305-e4b7edff9352.png)

**Comment by msull92** [comment]
This has since caused an issue with restarting the controller because it tries to load in the certs from the database into etcd and fails because that cert causes an error. So others can find this later I will attach the stack trace.

```
Traceback (most recent call last): 
 File "./manage.py", line 13, in <module> 
   execute_from_command_line(sys.argv) 
 File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line 
   utility.execute() 
 File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute 
   self.fetch_command(subcommand).run_from_argv(self.argv) 
 File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv  
   self.execute(*args, **options.__dict__) 
 File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute 
   output = self.handle(*args, **options) 
 File "/app/api/management/commands/load_db_state_to_etcd.py", line 15, in handle 
   obj.save() 
 File "/app/api/models.py", line 1049, in save 
   return super(Certificate, self).save(*args, **kwargs) 
 File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save 
   force_update=force_update, update_fields=update_fields) 
 File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base 
   update_fields=update_fields, raw=raw, using=using) 
 File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send 
   response = receiver(signal=self, sender=sender, **named) 
 File "/app/api/models.py", line 1166, in _etcd_publish_cert 
   _etcd_client.write('/deis/certs/{}/cert'.format(cert), cert.certificate) 
 File "/usr/lib/python2.7/site-packages/etcd/client.py", line 269, in write 
   response = self.api_execute(path, method, params=params) 
 File "/usr/lib/python2.7/site-packages/etcd/client.py", line 582, in api_execute 
   return self._handle_server_response(response) 
 File "/usr/lib/python2.7/site-packages/etcd/client.py", line 600, in _handle_server_response 
   raise etcd.EtcdException(resp) 
etcd.EtcdException 
```

To fix this, log into the database and remove the offending cert from the `api_certificate` table.

**Note:** Not sure if it will matter, but just for completeness; I am running a stateless platform on AWS. v1.11.1

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1225
