### ISSUE TITLE
`deis pull` fails on CoreOS beta

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4682]
On CoreOS alpha and beta, `deis pull deis/example-go` fails in the integration test suite with the controller stack trace below. I assume the difference is Docker 1.7.1 in CoreOS stable versus Docker 1.8.3 in CoreOS alpha and beta.
```
ct 28 15:52:22 deis-03 sh[3009]: File "/app/api/models.py", line 873, in new
Oct 28 15:52:22 deis-03 sh[3009]: release.publish()
Oct 28 15:52:22 deis-03 sh[3009]: File "/app/api/models.py", line 889, in publish
Oct 28 15:52:22 deis-03 sh[3009]: publish_release(source_image, self.config.values, self.image, deis_registry)
Oct 28 15:52:22 deis-03 sh[3009]: File "/app/registry/dockerclient.py", line 120, in publish_release
Oct 28 15:52:22 deis-03 sh[3009]: return client.publish_release(source, config, target, deis_registry)
Oct 28 15:52:22 deis-03 sh[3009]: File "/app/registry/dockerclient.py", line 53, in publish_release
Oct 28 15:52:22 deis-03 sh[3009]: self.push("{}/{}".format(self.registry, name), tag)
Oct 28 15:52:22 deis-03 sh[3009]: File "/app/registry/dockerclient.py", line 80, in push
Oct 28 15:52:22 deis-03 sh[3009]: log_output(stream)
Oct 28 15:52:22 deis-03 sh[3009]: File "/app/registry/dockerclient.py", line 108, in log_output
Oct 28 15:52:22 deis-03 sh[3009]: raise docker.errors.DockerException(chunk)
Oct 28 15:52:22 deis-03 sh[3009]: DockerException: {"errorDetail":{"message":"Failed to upload layer: Put http://172.17.8.101:5000/v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer: read /var/lib/docker/graph/_tmp/feed2912b4fc09fda676c3f31e1d9d3df702fdf9034e2a86b21d7b6052df2af9/837439512: bad file descriptor"},"error":"Failed to upload layer: Put http://172.17.8.101:5000/v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer: read /var/lib/docker/graph/_tmp/feed2912b4fc09fda676c3f31e1d9d3df702fdf9034e2a86b21d7b6052df2af9/837439512: bad file descriptor"}
```

**Comment by mboersma** [comment]
I can reproduce this with `docker` itself:
```console
core@deis-02 ~ $ docker pull deis/example-go
Using default tag: latest
Pulling repository docker.io/deis/example-go
6a014562119a: Download complete 
511136ea3c5a: Download complete 
5b9ac152d901: Download complete 
ba11eccd2ffe: Download complete 
Status: Image is up to date for deis/example-go:latest
docker.io/deis/example-go: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
core@deis-02 ~ $ docker tag deis/example-go:latest 172.17.8.100:5000/uphill-larkspur:v3
core@deis-02 ~ $ docker push 172.17.8.100:5000/uphill-larkspur:v3
The push refers to a repository [172.17.8.100:5000/uphill-larkspur] (len: 1)
Sending image list
Pushing repository 172.17.8.100:5000/uphill-larkspur (1 tags)
Image 511136ea3c5a already pushed, skipping
5b9ac152d901: Pushing [==================================================>] 4.076 MB/4.076 MB
Failed to upload layer: Put http://172.17.8.100:5000/v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer: read /var/lib/docker/graph/_tmp/f8906e37998f7bd3509c05b0ca04f66fe42a2da26d64e323ad44234d8dcadb01/014779463: bad file descriptor
core@deis-02 ~ $ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=835.1.0
VERSION_ID=835.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@deis-02 ~ $ docker --version
Docker version 1.8.3, build cedd534-dirty
```

**Comment by mboersma** [comment]
Another example with an image that was probably built with Docker 1.5.0, if that's relevant:
```console
core@deis-02 ~ $ docker pull mboersma/nodejs-hello
Using default tag: latest
latest: Pulling from mboersma/nodejs-hello
d634beec75db: Already exists 
dd14041e8984: Already exists 
5613b94d6dc3: Already exists 
cbb4e8c5dfbe: Already exists 
ddcf874ab575: Already exists 
4b2590015f5c: Already exists 
3b4f9d88b69d: Already exists 
56edfd86c04e: Already exists 
e3d0474ddd7e: Already exists 
f19eef338fcd: Already exists 
73d99ebbcfc8: Already exists 
4d8eb0a9eb41: Already exists 
32dace50ec13: Already exists 
dde7a097f1c9: Already exists 
390b066945d9: Already exists 
db35495cabd2: Already exists 
Digest: sha256:57dd46e6d2074fb104d5404a768885074359f203611f60fdcfeb865196921990
Status: Downloaded newer image for mboersma/nodejs-hello:latest
core@deis-02 ~ $ docker tag mboersma/nodejs-hello:latest 172.17.8.100:5000/uphill-larkspur:v5
core@deis-02 ~ $ docker push 172.17.8.100:5000/uphill-larkspur:v5
The push refers to a repository [172.17.8.100:5000/uphill-larkspur] (len: 1)
Sending image list
Pushing repository 172.17.8.100:5000/uphill-larkspur (1 tags)
Image d634beec75db already pushed, skipping
Image dd14041e8984 already pushed, skipping
5613b94d6dc3: Pushing [==================================================>] 123.2 MB/123.2 MB
Failed to upload layer: Put http://172.17.8.100:5000/v1/images/89f520140765dde349ca59584e63082ff38794e0a0a865abc28f4717f6ddde7b/layer: read /var/lib/docker/graph/_tmp/fffd1cdf600d8103f2e0b634dbb871ab39c7abc52b492076f8c1807e122870e6/226882810: bad file descriptor
```
Maybe the local Docker graph is corrupted, but if so it is easily triggered.

I can't reproduce this on a brand-new CoreOS alpha vagrant box from the coreos-vagrant project using Docker Hub, as another data point.

**Comment by bacongobbler** [comment]
this might possibly be related:
> # Docker 1.8.2
> - Fix ^C on docker pull.
> - Fix docker pull issues on client disconnection.
> - Fix goroutine leak pulling images from registry V2.

I'll try to reproduce on my end as well.

**Comment by bacongobbler** [comment]
I was able to reproduce this quite easily on the beta channel, though still trying to figure out what's causing this.

**Comment by bacongobbler** [comment]
Here's what I got after turning on DEBUG for the registry module:

```
bash-4.3# python manage.py shell
WARNING Cannot synchronize with etcd cluster
Python 2.7.10 (default, Aug 13 2015, 12:27:27)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from registry.dockerclient import DockerClient
>>> d = DockerClient()
>>> d.push('172.17.8.100:5000/deispullsample', 'v2')
INFO Pushing Docker image 172.17.8.100:5000/deispullsample:v2
DEBUG {"status":"The push refers to a repository [172.17.8.100:5000/deispullsample] (len: 1)"}

DEBUG {"status":"Sending image list"}

DEBUG {"status":"Pushing repository 172.17.8.100:5000/deispullsample (1 tags)"}

DEBUG {"status":"Image 511136ea3c5a already pushed, skipping"}

DEBUG {"status":"Pushing","progressDetail":{},"id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":528384},"progress":"528.4 kB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":1085440},"progress":"1.085 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":1642496},"progress":"1.642 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":2199552},"progress":"  2.2 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":2756608},"progress":"2.757 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":3313664},"progress":"3.314 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":3870720},"progress":"3.871 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":4075840},"progress":"4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Buffering to disk","progressDetail":{"current":4075840},"progress":"4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":69632,"total":4075840},"progress":"[\u003e                                                  ] 69.63 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":135168,"total":4075840},"progress":"[=\u003e                                                 ] 135.2 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":200704,"total":4075840},"progress":"[==\u003e                                                ] 200.7 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":266240,"total":4075840},"progress":"[===\u003e                                               ] 266.2 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":331776,"total":4075840},"progress":"[====\u003e                                              ] 331.8 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":397312,"total":4075840},"progress":"[====\u003e                                              ] 397.3 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":462848,"total":4075840},"progress":"[=====\u003e                                             ] 462.8 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":528384,"total":4075840},"progress":"[======\u003e                                            ] 528.4 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":593920,"total":4075840},"progress":"[=======\u003e                                           ] 593.9 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":659456,"total":4075840},"progress":"[========\u003e                                          ] 659.5 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":724992,"total":4075840},"progress":"[========\u003e                                          ]   725 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":790528,"total":4075840},"progress":"[=========\u003e                                         ] 790.5 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":856064,"total":4075840},"progress":"[==========\u003e                                        ] 856.1 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":921600,"total":4075840},"progress":"[===========\u003e                                       ] 921.6 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":987136,"total":4075840},"progress":"[============\u003e                                      ] 987.1 kB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1052672,"total":4075840},"progress":"[============\u003e                                      ] 1.053 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1118208,"total":4075840},"progress":"[=============\u003e                                     ] 1.118 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1183744,"total":4075840},"progress":"[==============\u003e                                    ] 1.184 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1249280,"total":4075840},"progress":"[===============\u003e                                   ] 1.249 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1314816,"total":4075840},"progress":"[================\u003e                                  ] 1.315 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1380352,"total":4075840},"progress":"[================\u003e                                  ]  1.38 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1445888,"total":4075840},"progress":"[=================\u003e                                 ] 1.446 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1511424,"total":4075840},"progress":"[==================\u003e                                ] 1.511 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1576960,"total":4075840},"progress":"[===================\u003e                               ] 1.577 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1642496,"total":4075840},"progress":"[====================\u003e                              ] 1.642 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1708032,"total":4075840},"progress":"[====================\u003e                              ] 1.708 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1773568,"total":4075840},"progress":"[=====================\u003e                             ] 1.774 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1839104,"total":4075840},"progress":"[======================\u003e                            ] 1.839 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1904640,"total":4075840},"progress":"[=======================\u003e                           ] 1.905 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":1970176,"total":4075840},"progress":"[========================\u003e                          ]  1.97 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2035712,"total":4075840},"progress":"[========================\u003e                          ] 2.036 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2101248,"total":4075840},"progress":"[=========================\u003e                         ] 2.101 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2166784,"total":4075840},"progress":"[==========================\u003e                        ] 2.167 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2232320,"total":4075840},"progress":"[===========================\u003e                       ] 2.232 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2297856,"total":4075840},"progress":"[============================\u003e                      ] 2.298 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2363392,"total":4075840},"progress":"[============================\u003e                      ] 2.363 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2428928,"total":4075840},"progress":"[=============================\u003e                     ] 2.429 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2494464,"total":4075840},"progress":"[==============================\u003e                    ] 2.494 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2560000,"total":4075840},"progress":"[===============================\u003e                   ]  2.56 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2625536,"total":4075840},"progress":"[================================\u003e                  ] 2.626 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2691072,"total":4075840},"progress":"[=================================\u003e                 ] 2.691 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2756608,"total":4075840},"progress":"[=================================\u003e                 ] 2.757 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2822144,"total":4075840},"progress":"[==================================\u003e                ] 2.822 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2887680,"total":4075840},"progress":"[===================================\u003e               ] 2.888 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":2953216,"total":4075840},"progress":"[====================================\u003e              ] 2.953 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3018752,"total":4075840},"progress":"[=====================================\u003e             ] 3.019 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3084288,"total":4075840},"progress":"[=====================================\u003e             ] 3.084 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3149824,"total":4075840},"progress":"[======================================\u003e            ]  3.15 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3215360,"total":4075840},"progress":"[=======================================\u003e           ] 3.215 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3280896,"total":4075840},"progress":"[========================================\u003e          ] 3.281 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3346432,"total":4075840},"progress":"[=========================================\u003e         ] 3.346 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3411968,"total":4075840},"progress":"[=========================================\u003e         ] 3.412 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3477504,"total":4075840},"progress":"[==========================================\u003e        ] 3.478 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3543040,"total":4075840},"progress":"[===========================================\u003e       ] 3.543 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3608576,"total":4075840},"progress":"[============================================\u003e      ] 3.609 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3674112,"total":4075840},"progress":"[=============================================\u003e     ] 3.674 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3739648,"total":4075840},"progress":"[=============================================\u003e     ]  3.74 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3805184,"total":4075840},"progress":"[==============================================\u003e    ] 3.805 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3870720,"total":4075840},"progress":"[===============================================\u003e   ] 3.871 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":3936256,"total":4075840},"progress":"[================================================\u003e  ] 3.936 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":4001792,"total":4075840},"progress":"[=================================================\u003e ] 4.002 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":4067328,"total":4075840},"progress":"[=================================================\u003e ] 4.067 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":4075840,"total":4075840},"progress":"[==================================================\u003e] 4.076 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"status":"Pushing","progressDetail":{"current":4075840,"total":4075840},"progress":"[==================================================\u003e] 4.076 MB/4.076 MB","id":"5b9ac152d901"}
DEBUG {"errorDetail":{"message":"Failed to upload layer: Put http://172.17.8.100:5000/v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer: read /var/lib/docker/graph/_tmp/a02c3ce9104b4b18c304f94ba25c0bed092bee880553b6e9c8e006b4ebf536a4/697891793: bad file descriptor"},"error":"Failed to upload layer: Put http://172.17.8.100:5000/v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer: read /var/lib/docker/graph/_tmp/a02c3ce9104b4b18c304f94ba25c0bed092bee880553b6e9c8e006b4ebf536a4/697891793: bad file descriptor"}
```

From dropping back onto the host running the controller, I take a look at that layer in question:

```
core@deis-02 ~ $ docker history 172.17.8.100:5000/deispullsample:v2
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
2a4e903d802d        32 minutes ago      /bin/sh -c #(nop) ENV DEIS_APP=deispullsample   0 B
6a014562119a        13 months ago       /bin/sh -c #(nop) ENTRYPOINT [/usr/local/bin/   0 B
ba11eccd2ffe        13 months ago       /bin/sh -c #(nop) EXPOSE map[8080/tcp:{}]       0 B
5b9ac152d901        13 months ago       /bin/sh -c #(nop) ADD file:f110de9d842d7fb5b4   4.072 MB
511136ea3c5a        2 years ago                                                         0 B                 Imported from -
```

Not sure why it's getting a bad file descriptor... Anyone got any ideas?

**Comment by bacongobbler** [comment]
I found something more interesting in the registry:

```
2015-11-02 19:09:17,563 ERROR: Exception on /v1/images/5b9ac152d901eb71c717df2fdea84dace30f488d7a0a7da5cd2ffa13b2760ef5/layer [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/__init__.py", line 279, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 280, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker_registry/images.py", line 222, in put_image_layer
    store.stream_write(layer_path, sr)
  File "/usr/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 144, in stream_write
    raise e
NoMoreData: No more data after: None
```

**Comment by bacongobbler** [comment]
Note that this works perfectly fine with a v2 registry, so it's likely some bug in the (deprecated) v1 registry.

**Comment by bacongobbler** [comment]
This also just occurred in coreos-test-alpha: https://ci.deis.io/job/test-coreos-alpha/432/consoleFull#682192135502066c60b2236c09cc9bf8

Getting #3814 out the door ASAP will help us when we eventually need to upgrade to v1.8.3, but for now we're probably fine.

**Comment by mboersma** [comment]
> for now we're probably fine

Agreed, although at some point CoreOS will promote one of those builds to the stable channel and then Deis will need a fix for this. I removed the milestone but left the "showstopper" tag on so it's clear this is something to attend to ASAP. Thanks for all the debugging and logs @bacongobbler.

**Comment by mboersma** [comment]
This appears to have been fixed in CoreOS itself; we've upgraded well past this point and `deis pull` succeeds in integration testing.
