### ISSUE TITLE
Panic on `deis create` following tutorial

### ISSUE THREAD

**Issue by ngauthier** [deis/deis#4690]
Hi all,

I've paniced the deis client while following the tutorial with vagrant:

```
nick@nite:~/workspace/example-ruby-sinatra$ deis apps:create
Creating Application... panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x548d9d]

goroutine 1 [running]:
github.com/deis/deis/client/controller/models/apps.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/controller/models/apps/apps.go:43 +0x39d
github.com/deis/deis/client/cmd.AppCreate(0x0, 0x0, 0x0, 0x0, 0xc820016efb, 0x4, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/apps.go:26 +0x181
github.com/deis/deis/client/parser.appCreate(0xc82000a3f0, 0x1, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/parser/apps.go:92 +0x42c
github.com/deis/deis/client/parser.Apps(0xc82000a3f0, 0x1, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/parser/apps.go:30 +0x530
main.Command(0xc82000a3f0, 0x1, 0x1, 0x586db0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/deis.go:87 +0xdc6
main.main()
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/deis.go:18 +0x60

goroutine 6 [runnable]:
github.com/deis/deis/client/cmd.progress.func1(0xc820017000, 0x4, 0x4, 0xc82001ab40, 0xc820168970, 0x3, 0xc82001aae0)
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/utils.go:20
created by github.com/deis/deis/client/cmd.progress
	/home/jenkins/workspace/build-deis-cli-installer-linux/src/github.com/deis/deis/client/cmd/utils.go:34 +0x166
```

I didn't see an existing issue.

**Comment by ngauthier** [comment]
I was on step 3 here http://deis.io/get-deis/

**Comment by ngauthier** [comment]
If I give it an id on the cli I get the same panic.

**Comment by bacongobbler** [comment]
Hey @ngauthier! Which version of the client are you using? If you're on v1.11.2, according to that stack trace it's pointing to https://github.com/deis/deis/blob/v1.11.2/client/controller/models/apps/apps.go#L43.

**Comment by ngauthier** [comment]
Huh, somehow I installed in 10 minutes ago yet I'm on 1.11.1.

**Comment by ngauthier** [comment]
http://deis.io/deis-cli/install.sh installs 1.11.1

**Comment by ngauthier** [comment]
Upped to 1.11.2 and problem persists.

**Comment by bacongobbler** [comment]
@ngauthier if you want to PM me on IRC a tmate session or a google hangout I'd be happy to check this out with you.

**Comment by ngauthier** [comment]
I'm at ContainerDays NYC and we're just breaking for lunch, but we can check it out after. Also @technosophos and a few others are here so maybe I'll bug them first :)

**Comment by sgoings** [comment]
You should bug @krancour if you can find him!

**Comment by ngauthier** [comment]
Found the bug. Creating test, PR incoming!

**Comment by ngauthier** [comment]
Couldn't make a test, it depends on ENV vars and files on the FS :(
