### ISSUE TITLE
Vagrantfile broken

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4691]
I'm having trouble using the vagrant provisioner, my guess is due to the changes that most recently went in with #4562.

```
$ vagrant status # up produces this error too
/opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/requirement.rb:90:in `parse': Illformed requirement ["-e \e[0;33m\e[0m"] (Gem::Requirement::BadRequirementError)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/requirement.rb:120:in `block in initialize'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/requirement.rb:120:in `map!'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/requirement.rb:120:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:264:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:264:in `block in find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:262:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:262:in `find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:167:in `block in machine_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:200:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:200:in `machine_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:45:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:612:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:200:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/status/command.rb:20:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

I added some debugging info to Vagrant itself and it shows:

```
WARN box_collection: box name: coreos--e , providers: [:virtualbox], version: -e
```

Looks like sourcing utils.sh (COREOS_VERSION, et. al) from the Vagrantfile isn't quite working as expected.

**Comment by sgoings** [comment]
Looks like Ruby is executing the shell script snippet with "sh" not "bash":

```
# stderr
sh: 3: [...]/go/src/github.com/deis/deis/contrib/utils.sh: function: not found
sh: 5: [...]/go/src/github.com/deis/deis/contrib/utils.sh: Syntax error: "}" unexpected

# stdout
-e
```

**Comment by carmstrong** [comment]
I'm unable to produce this off HEAD:
```console
➜  deis git:(master) vagrant --version
Vagrant 1.7.2
```

Out of curiosity, I'll upgrade to Vagrant 1.7.4 and see if I see it.

**Comment by bacongobbler** [comment]
That's odd. It works fine for me on master:

```
$ make discovery-url
Wrote https://discovery.etcd.io/9d3210f7327c09b78bf92d61aba71667 to contrib/coreos/user-data
$ vu
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Box 'coreos-stable' could not be found. Attempting to find and install...
    deis-01: Box Provider: virtualbox
    deis-01: Box Version: 766.4.0
==> deis-01: Loading metadata for box 'http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json'
    deis-01: URL: http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json
==> deis-01: Adding box 'coreos-stable' (v766.4.0) for provider: virtualbox
    deis-01: Downloading: http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.box
    deis-01: Calculating and comparing box checksum...
==> deis-01: Successfully added box 'coreos-stable' (v766.4.0) for 'virtualbox'!
==> deis-01: Importing base box 'coreos-stable'...
==> deis-01: Matching MAC address for NAT networking...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: Setting the name of the VM: deis_deis-01_1446140336668_1946
==> deis-01: Fixed port collision for 22 => 2222. Now on port 2202.
==> deis-01: Clearing any previously set network interfaces...
==> deis-01: Preparing network interfaces based on configuration...
    deis-01: Adapter 1: nat
    deis-01: Adapter 2: hostonly
==> deis-01: Forwarding ports...
    deis-01: 22 => 2202 (adapter 1)
==> deis-01: Running 'pre-boot' VM customizations...
==> deis-01: Booting VM...
==> deis-01: Waiting for machine to boot. This may take a few minutes...
    deis-01: SSH address: 127.0.0.1:2202
    deis-01: SSH username: core
    deis-01: SSH auth method: private key
    deis-01: Warning: Connection timeout. Retrying...
==> deis-01: Machine booted and ready!
==> deis-01: Setting hostname...
==> deis-01: Configuring and enabling network interfaces...
==> deis-01: Running provisioner: file...
==> deis-01: Running provisioner: shell...
    deis-01: Running: /var/folders/xw/311wmd6j3wjbq_67wjmfkvl80000gn/T/vagrant-shell20151029-27917-1jn8wgy.sh
==> deis-01: Running provisioner: shell...
    deis-01: Running: inline script
==> deis-02: Running triggers before up...
==> deis-02: Box 'coreos-stable' could not be found. Attempting to find and install...
    deis-02: Box Provider: virtualbox
    deis-02: Box Version: 766.4.0
==> deis-02: Loading metadata for box 'http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json'
    deis-02: URL: http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json
==> deis-02: Adding box 'coreos-stable' (v766.4.0) for provider: virtualbox
==> deis-02: Importing base box 'coreos-stable'...
==> deis-02: Matching MAC address for NAT networking...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: Setting the name of the VM: deis_deis-02_1446140366339_93854
==> deis-02: Fixed port collision for 22 => 2222. Now on port 2203.
==> deis-02: Clearing any previously set network interfaces...
==> deis-02: Preparing network interfaces based on configuration...
    deis-02: Adapter 1: nat
    deis-02: Adapter 2: hostonly
==> deis-02: Forwarding ports...
    deis-02: 22 => 2203 (adapter 1)
==> deis-02: Running 'pre-boot' VM customizations...
==> deis-02: Booting VM...
==> deis-02: Waiting for machine to boot. This may take a few minutes...
    deis-02: SSH address: 127.0.0.1:2203
    deis-02: SSH username: core
    deis-02: SSH auth method: private key
    deis-02: Warning: Connection timeout. Retrying...
==> deis-02: Machine booted and ready!
==> deis-02: Setting hostname...
==> deis-02: Configuring and enabling network interfaces...
==> deis-02: Running provisioner: file...
==> deis-02: Running provisioner: shell...
    deis-02: Running: /var/folders/xw/311wmd6j3wjbq_67wjmfkvl80000gn/T/vagrant-shell20151029-27917-1tbiy33.sh
==> deis-02: Running provisioner: shell...
    deis-02: Running: inline script
==> deis-03: Running triggers before up...
==> deis-03: Box 'coreos-stable' could not be found. Attempting to find and install...
    deis-03: Box Provider: virtualbox
    deis-03: Box Version: 766.4.0
==> deis-03: Loading metadata for box 'http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json'
    deis-03: URL: http://stable.release.core-os.net/amd64-usr/766.4.0/coreos_production_vagrant.json
==> deis-03: Adding box 'coreos-stable' (v766.4.0) for provider: virtualbox
==> deis-03: Importing base box 'coreos-stable'...
==> deis-03: Matching MAC address for NAT networking...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: Setting the name of the VM: deis_deis-03_1446140394677_83552
==> deis-03: Fixed port collision for 22 => 2222. Now on port 2204.
==> deis-03: Clearing any previously set network interfaces...
==> deis-03: Preparing network interfaces based on configuration...
    deis-03: Adapter 1: nat
    deis-03: Adapter 2: hostonly
==> deis-03: Forwarding ports...
    deis-03: 22 => 2204 (adapter 1)
==> deis-03: Running 'pre-boot' VM customizations...
==> deis-03: Booting VM...
==> deis-03: Waiting for machine to boot. This may take a few minutes...
    deis-03: SSH address: 127.0.0.1:2204
    deis-03: SSH username: core
    deis-03: SSH auth method: private key
    deis-03: Warning: Connection timeout. Retrying...
==> deis-03: Machine booted and ready!
==> deis-03: Setting hostname...
==> deis-03: Configuring and enabling network interfaces...
==> deis-03: Running provisioner: file...
==> deis-03: Running provisioner: shell...
    deis-03: Running: /var/folders/xw/311wmd6j3wjbq_67wjmfkvl80000gn/T/vagrant-shell20151029-27917-p6k4tg.sh
==> deis-03: Running provisioner: shell...
    deis-03: Running: inline script
$ vs deis-01
 * *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
 * *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
  *   *****  * *      d    d  e         i          s
 * *  *   * *   *     d   d   e    e    i    s    s
***** *****  * *     ddddd   eeeeeee iiiiiii  ssss

Welcome to Deis			Powered by CoreOS
core@deis-01 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=766.4.0
VERSION_ID=766.4.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.4.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by carmstrong** [comment]
Confirmed working on 1.7.4. @sgoings is :cactus: 

```console
➜  deis git:(master) vagrant --version
Vagrant 1.7.4
➜  deis git:(master) vagrant status
Current machine states:

deis-01                   running (virtualbox)
deis-02                   running (virtualbox)
deis-03                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by sgoings** [comment]
Might be a difference between Mac and Ubuntu default shells or handling within Ruby? This is happening on the Jenkins build nodes. Also see: http://shiroyasha.github.io/running-shell-commands-from-ruby.html

**Comment by carmstrong** [comment]
Yeah, probably something to do with the Jenkins node's system.

**Comment by sgoings** [comment]
No, it's not Jenkins - it would be Ubuntu. I can confirm this is fully reproducible logged into the box.

**Comment by bacongobbler** [comment]
Can we try changing [this line](https://github.com/deis/deis/blob/master/Vagrantfile#L19) to use `/usr/bin/env bash` instead of `.`? Perhaps the default shell is used when `.` is invoked.

**Comment by bacongobbler** [comment]
Something that looks very similar to what I'm alluding to: http://askubuntu.com/a/25530

**Comment by sgoings** [comment]
I'm fixin' her up. :smile:
