### ISSUE TITLE
`deis pull` panic on Mac OS X

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4698]
`deis pull` panics for me consistently on master or the v1.12.0-rc1 branch, whether I build `deis` locally or use the binary installer from `curl -sSL http://deis.io/deis-cli/install.sh | sh -s 1.12.0`:
```console
$ ./deis pull mboersma/nodejs-hello -a zeroed-rosewood
Creating build... panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1162e5]

goroutine 1 [running]:
github.com/deis/deis/client/cmd.BuildsCreate(0x7fff5fbff955, 0xf, 0x7fff5fbff93c, 0x15, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/cmd/builds.go:66 +0x295
github.com/deis/deis/client/parser.buildsCreate(0xc82000a1f0, 0x4, 0x4, 0x0, 0x0)
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/builds.go:98 +0x37c
github.com/deis/deis/client/parser.Builds(0xc82000a1f0, 0x4, 0x4, 0x0, 0x0)
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/builds.go:23 +0x12f
main.Command(0xc82000a1f0, 0x4, 0x4, 0x187fe0)
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:93 +0x1404
main.main()
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:18 +0x60

goroutine 6 [runnable]:
github.com/deis/deis/client/cmd.progress.func1(0xc820010e80, 0x4, 0x4, 0xc82001aa20, 0xc820148660, 0x3, 0xc82001a9c0)
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/cmd/utils.go:20
created by github.com/deis/deis/client/cmd.progress
	/Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/cmd/utils.go:34 +0x166
```
The v1.11.2 `deis` Mac OS X binary works fine, however, and this doesn't seem to occur on Linux.

**Comment by Joshua-Anderson** [comment]
I suspect this has something to do with #4606, but I don't have an OS X machine to debug with so I can't test my suspicions. I think `procfileMap` may somehow not be initialized when yaml isn't parsed. Maybe try `procfileMap := make(map[string]string)` [here](https://github.com/deis/deis/blob/master/client/cmd/builds.go#L47) instead of var.
