### ISSUE TITLE
After v1.12.1 upgrade. Deployment is broken. 

### ISSUE THREAD

**Issue by stuszynski** [deis/deis#4766]
Hi,

after upgrade from v1.11.2 to v1.12.1 I encounter some strange issue. We are running stateless on AWS + RDS + S3.

At the end of the deployment.

```
-----> Launching...
2015/11/27 08:53:38 failed retrieving config from controller: <h1>Server Error (500)</h1>
To ssh://git@[our-domain]:2222/test-kibana.git
 * [new branch]      master -> master
```

In deis-controller:

```
Nov 27 08:53:37 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: INFO test-kibana: build test-kibana-6e2a48f created
Nov 27 08:53:37 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: INFO test-kibana: release test-kibana-v4 created
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: INFO [test-kibana]: stuszynski deployed 7c66fd6
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: ERROR Internal Server Error: /v1/hooks/build
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: Traceback (most recent call last):
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: return view_func(*args, **kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: return self.dispatch(request, *args, **kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: response = self.handle_exception(exc)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: response = handler(request, *args, **kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/views.py", line 393, in create
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: super(BuildHookViewSet, self).create(request, *args, **kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/views.py", line 117, in create
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: self.perform_create(serializer)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/viewsets.py", line 21, in perform_create
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: self.post_save(obj)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/views.py", line 400, in post_save
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: build.create(self.user)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/models.py", line 760, in create
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: source_version=source_version)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/models.py", line 873, in new
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: release.publish()
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/api/models.py", line 889, in publish
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: publish_release(source_image, self.config.values, self.image, deis_registry)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/registry/dockerclient.py", line 119, in publish_release
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: client = DockerClient()
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/app/registry/dockerclient.py", line 22, in __init__
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: self.client = docker.Client(version='auto')
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/docker/client.py", line 77, in __init__
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: self._version = self._retrieve_server_version()
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: File "/usr/lib/python2.7/site-packages/docker/client.py", line 97, in _retrieve_server_version
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: 'Error while fetching server API version: {0}'.format(e)
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
Nov 27 08:53:38 ip-172-31-14-185.eu-west-1.compute.internal sh[16382]: 172.31.18.33 "POST /v1/hooks/build HTTP/1.1" 500 27 "deis-builder"
```

Deis-registry around error:
```
Nov 27 08:53:22 ip-172-31-35-5.eu-west-1.compute.internal sh[7783]: 172.31.18.33 - - [27/Nov/2015:08:53:22 +0000] "GET /v2/ HTTP/1.1" 404 233 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.7-coreos-r1 os/linux arch/amd64"
Nov 27 08:53:26 ip-172-31-35-5.eu-west-1.compute.internal sh[7783]: 27/Nov/2015:08:53:26 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Nov 27 08:53:26 ip-172-31-35-5.eu-west-1.compute.internal sh[7783]: 172.31.18.33 - - [27/Nov/2015:08:53:26 +0000] "PUT /v1/repositories/test-kibana/ HTTP/1.1" 200 2 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.7-coreos-r1 os/linux arch/amd64"
```

no errors in `deis-builder`. 

I also had the same issue after fresh install of v1.12.1 on DO couple of hours ago.  What do you think of it? Thanks in advance.

**Comment by stuszynski** [comment]
Is this posible to be related to this PR? #4767 I had to change 
```
gateway/host=s3-eu-west-1.amazonaws.com \
gateway/port=80
```

to 

```
gateway/host=s3-eu-west-1.amazonaws.com \
gateway/port=443
```

to make registry run. If not it stuck on creating bucket and prompt: ```
Nov 26 16:39:48 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: registry: creating bucket
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: Traceback (most recent call last):
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/app/bin/create_bucket", line 25, in <module>
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: conn.create_bucket(name)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: data=data)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: retry_handler=retry_handler
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1068, in make_request
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: retry_handler=retry_handler)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 942, in _mexe
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: request.body, request.headers)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 1001, in request
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self._send_request(method, url, body, headers)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self.endheaders(body)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self._send_output(message_body)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self.send(msg)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 812, in send
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self.connect()
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/httplib.py", line 1212, in connect
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: server_hostname=server_hostname)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: _context=self)
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/ssl.py", line 566, in __init__
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self.do_handshake()
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: self._sslobj.do_handshake()
Nov 26 16:44:37 ip-172-31-35-5.eu-west-1.compute.internal sh[4405]: ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)
```

**Comment by stuszynski** [comment]
Sorry. It was my fault. I didn't upgraded deisctl before platform install and start.
