### ISSUE TITLE
Registry fails to start after 1.12.1 upgrade (and therefore, controller and builder as well)

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4772]
Getting this error after doing an in place upgrade to 1.21.1 (stateless platform):

```bash
 $ fleetctl journal -f deis-controller
-- Logs begin at Sun 2015-11-29 02:14:09 UTC. --
Nov 30 11:52:43 ip-10-21-2-25.ec2.internal sh[5827]: 2015-11-30T11:52:43Z b662590126a9 confd[234]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Nov 30 11:52:43 ip-10-21-2-25.ec2.internal sh[5827]: controller: waiting for confd to write initial templates...
Nov 30 11:52:53 ip-10-21-2-25.ec2.internal sh[5827]: 2015-11-30T11:52:53Z b662590126a9 confd[239]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
Nov 30 11:52:53 ip-10-21-2-25.ec2.internal sh[5827]: controller: waiting for confd to write initial templates...
Nov 30 11:53:03 ip-10-21-2-25.ec2.internal sh[5827]: 2015-11-30T11:53:03Z b662590126a9 confd[244]: ERROR template: confd_settings.py:30:58: executing "confd_settings.py" at <getv "/deis/registry...>: error calling getv: key does not exist
```

The missing key seems to be `/deis/registry/host`

```bash
core@ip-10-21-1-116 ~ $ etcdctl get /deis/registry/host
Error:  100: Key not found (/deis/registry/host) [86237503]
```

The problem seems to be that the registry is not starting and has a bug at the create-bucket step:

```bash
Nov 30 11:51:13 ip-10-21-2-84.ec2.internal systemd[1]: deis-registry@1.service holdoff time over, scheduling restart.
Nov 30 11:51:13 ip-10-21-2-84.ec2.internal systemd[1]: Starting deis-registry...
Nov 30 11:51:13 ip-10-21-2-84.ec2.internal etcdctl[30003]: Error:  105: Key already exists (/deis/cache) [86233102]
Nov 30 11:51:13 ip-10-21-2-84.ec2.internal systemd[1]: Started deis-registry.
Nov 30 11:51:14 ip-10-21-2-84.ec2.internal sh[30040]: registry: environment ETCD=10.21.2.84:4001 ETCD_PATH=/deis/registry HOST_ETCD_PATH=/deis/registry/hosts/10.21.2.84 ETCD_TTL=20 REGISTRY_PORT=5000 EXTERNAL_PORT=5000 BUCKET_NAME=registry
Nov 30 11:51:52 ip-10-21-2-84.ec2.internal sh[30040]: registry: creating bucket
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: Traceback (most recent call last):
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/app/bin/create_bucket", line 25, in <module>
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: conn.create_bucket(name)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: data=data)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: retry_handler=retry_handler
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1068, in make_request
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: retry_handler=retry_handler)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 942, in _mexe
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: request.body, request.headers)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 1001, in request
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self._send_request(method, url, body, headers)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self.endheaders(body)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self._send_output(message_body)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self.send(msg)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 812, in send
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self.connect()
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/httplib.py", line 1212, in connect
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: server_hostname=server_hostname)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: _context=self)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/ssl.py", line 566, in __init__
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self.do_handshake()
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: self._sslobj.do_handshake()
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal sh[30040]: ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)
Nov 30 11:54:44 ip-10-21-2-84.ec2.internal systemd[1]: deis-registry@1.service: main process exited, code=exited, status=1/FAILURE
N
```

I already have an S3 bucket (this is an upgrade) so not sure why it's trying to create a new one actually.

**Comment by olalonde** [comment]
Possibly related: https://github.com/deis/deis/issues/4766

**Comment by stuszynski** [comment]
@olalonde I had similar issue.  I changed port from 80 to 443 in stores's gateway/port variable which solved this for me:

```
deisctl config store set gateway/accessKey=<key> \
                           gateway/secretKey=<key> \
                           gateway/host=s3.amazonaws.com \
                           gateway/port=443
```

**Comment by bacongobbler** [comment]
fixed.

**Comment by rstacruz** [comment]
still happens to me in deis 1.12.2 on AWS EC2 (with ceph).

**Comment by monaka** [comment]
I also got this issue Deis 1.12.2 on Azure (with ceph).

**Comment by rstacruz** [comment]
for the curious, I migrated our cluster to a stateless Deis setup. it's much more stable compared to the stateful Ceph setup.
