### ISSUE TITLE
Registry fails to connect to s3

### ISSUE THREAD

**Issue by antonversal** [deis/deis#4779]
I'm trying to setup deis with `Ceph`. Followed the guide and when I start `deisctl start stateless-platform` it stucks on 'deis-builder.service'. Checking logs I found out that s3 requires AWS4-HMAC-SHA256.   
```
Dec 04 21:07:14 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: Starting deis-registry...
Dec 04 21:07:14 ip-10-21-10-18.eu-central-1.compute.internal etcdctl[22474]: Error:  105: Key already exists (/deis/cache) [15902]
Dec 04 21:07:14 ip-10-21-10-18.eu-central-1.compute.internal sh[22554]: deis-registry
Dec 04 21:07:14 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: Started deis-registry.
Dec 04 21:07:15 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: registry: environment ETCD=10.21.10.18:4001 ETCD_PATH=/deis/registry HOST_ETCD_PATH=/deis/registry/hosts/10.21.10.18 ETCD_TTL=20 REGISTRY_PORT=5000 EXTERNAL_PORT=5000 BUCKET_NAME=registry
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: registry: creating bucket
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: Traceback (most recent call last):
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: File "/app/bin/create_bucket", line 21, in <module>
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: conn.create_bucket(name)
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: response.status, response.reason, body)
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: <?xml version="1.0" encoding="UTF-8"?>
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal sh[22598]: <Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
<RequestId>62A5744DE682DF19</RequestId><HostId>mUTV9Y8Nz7/okTQHVZyo7FJQmg8wdjIZtlA4hiTTEDojgZkJvEeH82Z5Jeaav2i85XiPLFyG7B8=</HostId></Error>
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: deis-registry@1.service: Main process exited, code=exited, status=1/FAILURE
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: deis-registry@1.service: Unit entered failed state.
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: deis-registry@1.service: Failed with result 'exit-code'.
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal docker[22864]: Error response from daemon: no such id: deis-registry
Dec 04 21:07:36 ip-10-21-10-18.eu-central-1.compute.internal docker[22864]: Error: failed to stop containers: [deis-registry]
Dec 04 21:07:41 ip-10-21-10-18.eu-central-1.compute.internal systemd[1]: deis-registry@1.service: Service hold-off time over, scheduling restart.
```

**Comment by antonversal** [comment]
the issue is solved i set:
```
deisctl config store/gateway set host=s3.eu-central-1.amazonaws.com port=443
```
it should be stated in documentation
