### ISSUE TITLE
Controller fails to start after stateless-platform upgrade to 1.12.2 with "no more machines in the cluster"

### ISSUE THREAD

**Issue by keitaroinc** [deis/deis#4798]
After upgrading our stateless Deis cluster from 1.12.1 to 1.12.2, the deis controller is not starting throwing an etcd related issue (it seems) - "no more machines in the cluster". The deis-builder component is stuck in start-post.

Log:
```
Dec 14 23:57:21 ip-172-30-2-162.ec2.internal systemd[1]: Starting deis-controller...
Dec 14 23:57:21 ip-172-30-2-162.ec2.internal systemd[1]: Started deis-controller.
Dec 14 23:57:42 ip-172-30-2-162.ec2.internal sh[2276]: controller: running etcd data migrations...
Dec 14 23:57:42 ip-172-30-2-162.ec2.internal sh[2276]: controller: done running etcd data migrations.
Dec 14 23:57:43 ip-172-30-2-162.ec2.internal sh[2276]: Syncing...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Creating tables ...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installing custom SQL ...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installing indexes ...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installed 0 object(s) from 0 fixture(s)
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Migrating...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Running migrations for authtoken:
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Nothing to migrate.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Loading initial data for authtoken.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installed 0 object(s) from 0 fixture(s)
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Running migrations for api:
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Nothing to migrate.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Loading initial data for api.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installed 0 object(s) from 0 fixture(s)
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Running migrations for guardian:
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Nothing to migrate.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - Loading initial data for guardian.
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Installed 0 object(s) from 0 fixture(s)
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Synced:
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.admin
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.auth
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.contenttypes
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.humanize
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.messages
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.sessions
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.sites
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django.contrib.staticfiles
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > django_auth_ldap
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > json_field
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > rest_framework
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > south
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > corsheaders
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > registry
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: > web
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Migrated:
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - rest_framework.authtoken
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - api
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: - guardian
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [121] [INFO] Starting gunicorn 19.3.0
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [121] [INFO] Listening at: http://0.0.0.0:8000 (121)
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [121] [INFO] Using worker: sync
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [125] [INFO] Booting worker with pid: 125
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [126] [INFO] Booting worker with pid: 126
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [127] [INFO] Booting worker with pid: 127
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [128] [INFO] Booting worker with pid: 128
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [129] [INFO] Booting worker with pid: 129
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [130] [INFO] Booting worker with pid: 130
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [131] [INFO] Booting worker with pid: 131
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [132] [INFO] Booting worker with pid: 132
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: Publishing DB state to etcd...
Dec 14 23:57:44 ip-172-30-2-162.ec2.internal sh[2276]: [2015-12-14 23:57:44 +0000] [133] [INFO] Booting worker with pid: 133
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: Traceback (most recent call last):
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "./manage.py", line 13, in <module>
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: execute_from_command_line(sys.argv)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: utility.execute()
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: self.fetch_command(subcommand).run_from_argv(self.argv)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: self.execute(*args, **options.__dict__)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: output = self.handle(*args, **options)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/app/api/management/commands/load_db_state_to_etcd.py", line 15, in handle
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: obj.save()
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/app/api/models.py", line 1033, in save
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: return super(Certificate, self).save(*args, **kwargs)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: force_update=force_update, update_fields=update_fields)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: update_fields=update_fields, raw=raw, using=using)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: response = receiver(signal=self, sender=sender, **named)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/app/api/models.py", line 1150, in _etcd_publish_cert
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: _etcd_client.write('/deis/certs/{}/cert'.format(cert), cert.certificate)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 269, in write
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: response = self.api_execute(path, method, params=params)
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 576, in api_execute
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: self._base_uri = self._next_server()
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 534, in _next_server
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: raise etcd.EtcdException('No more machines in the cluster')
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal sh[2276]: etcd.EtcdException: No more machines in the cluster
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal systemd[1]: deis-controller.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal systemd[1]: deis-controller.service: Unit entered failed state.
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal systemd[1]: deis-controller.service: Failed with result 'exit-code'.
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal docker[2539]: Error response from daemon: no such id: deis-controller
Dec 14 23:57:45 ip-172-30-2-162.ec2.internal docker[2539]: Error: failed to stop containers: [deis-controller]
```

**Comment by bacongobbler** [comment]
@keitaroinc what is the status of `etcdctl cluster-health` on one of the nodes? Seems like the controller attempted to connect to the cluster but none of the machines responded.

**Comment by keitaroinc** [comment]
@bacongobbler the etcd cluster is healthy:

```
core@ip-172-30-0-169 ~ $ etcdctl cluster-health
member e003bed4571ec457 is healthy: got healthy result from http://172.30.0.169:2379
member f63908d65bcdad6a is healthy: got healthy result from http://172.30.1.187:2379
member fac4c8173843dc37 is healthy: got healthy result from http://172.30.2.162:2379
cluster is healthy
```

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant (etcd is gone) so I'm closing this as fixed in v2.
