### ISSUE TITLE
Controller/Builder not creating new releases.

### ISSUE THREAD

**Issue by obmarg** [deis/deis#4841]
We've got a 1.12 cluster that has been running for a while.

Yesterday, one of our applications was sitting on v52.  We attempted to release a new version of the application as normal.  We pushed to git, the builder ran and reported success at the end, only it reported we had just deployed v52.  Looking in the `deis releases` output for this application showed no record of the deploy we'd just made, just v52 from a few weeks ago when we last released.

We've since tried a few of our other applications - one of them did not show this behaviour, however most of them have since started showing this behaviour (including one application that was successfully deployed yesterday).

I can find no evidence of problems with the controller - it's logs show that it's getting called to by the builder as expected at the end of the builds, and I can't find any other evidence of problems.

The builder is a bit trickier to diagnose - every service on the machine appears to be running fine, except I'm no longer able to ssh in to it to check the logs from the builder.

Any ideas what could be causing this?

**Comment by bacongobbler** [comment]
@obmarg do you have logs that show this behaviour?

**Comment by obmarg** [comment]
No logs unfortunately.  The cluster that was exhibiting this behaviour got rebuilt about 2 weeks ago.

**Comment by sstarcher** [comment]
I just ran into what looks to be the same situation.  Version 42 was released 2 weeks ago, but anytime I deploy again to Deis it attempts to build version 42 again.  This has happened 3 times in a row and I'm trying to debug why.

 deis releases -a public   
```                                                                                                                              
=== public Releases
v42	2016-01-28T18:14:07UTC	jenkins deployed db1557a
v41	2016-01-28T18:12:21UTC	sstarcher changed deis_whitelist
v40	2016-01-28T18:04:52UTC	sstarcher added HEALTHCHECK_URL
v39	2016-01-28T18:03:52UTC	sstarcher deleted derp
```

Jenkins build logs
```
remote: -----> Pushing image to private registry        
remote:         
remote: -----> Launching...         
remote:        done, public:v42 deployed to Deis        
remote:         
remote:        http://public.blue-cluster.private        
remote:         
remote:        To learn more, use `deis help` or visit http://deis.io        
remote:         
To ssh://git@deis.cluster.private:2222/public.git
```

**Comment by nathansamson** [comment]
I had similar weird behaviour lately when the database was running multiple times, and the controller was flapping between the 2 hosts.

Can you run `deisctl journal controller` and log the last lines here or in a gist / pastebin?

**Comment by sstarcher** [comment]
Interesting the controller says it's v43
```
Feb 18 14:31:34 ip-10-0-30-167.ec2.internal sh[15061]: INFO public: build public-501516c created
Feb 18 14:31:34 ip-10-0-30-167.ec2.internal sh[15061]: INFO public: release public-v43 created
Feb 18 14:31:34 ip-10-0-30-167.ec2.internal sh[15061]: INFO [public]: jenkins deployed 01537c6
Feb 18 14:31:34 ip-10-0-30-167.ec2.internal sh[15061]: INFO Pulling Docker image 10.0.20.95:5000/public:git-01537c6d
Feb 18 14:31:49 ip-10-0-30-167.ec2.internal sh[15061]: INFO Tagging Docker image 10.0.20.95:5000/public:git-01537c6d as public:git-01537c6d
Feb 18 14:31:49 ip-10-0-30-167.ec2.internal sh[15061]: INFO Building Docker image 10.0.20.95:5000/public:v43
Feb 18 14:31:51 ip-10-0-30-167.ec2.internal sh[15061]: INFO Pushing Docker image 10.0.20.95:5000/public:v43
Feb 18 14:32:27 ip-10-0-30-167.ec2.internal sh[15061]: WARNING Not Found: /
Feb 18 14:32:27 ip-10-0-30-167.ec2.internal sh[15061]: 10.0.20.95 "GET / HTTP/1.0" 404 74 "Sensu-HTTP-Check"
Feb 18 14:33:08 ip-10-0-30-167.ec2.internal sh[15061]: WARNING public: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 3.0 seconds
Feb 18 14:33:08 ip-10-0-30-167.ec2.internal sh[15061]: WARNING [public]: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 3.0 seconds
Feb 18 14:33:11 ip-10-0-30-167.ec2.internal sh[15061]: WARNING public: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 15.0 seconds
Feb 18 14:33:11 ip-10-0-30-167.ec2.internal sh[15061]: WARNING [public]: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 15.0 seconds
Feb 18 14:33:26 ip-10-0-30-167.ec2.internal sh[15061]: WARNING public: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 30.0 seconds
Feb 18 14:33:26 ip-10-0-30-167.ec2.internal sh[15061]: WARNING [public]: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.1'); trying again in 30.0 seconds
Feb 18 14:33:27 ip-10-0-30-167.ec2.internal sh[15061]: WARNING Not Found: /
Feb 18 14:33:27 ip-10-0-30-167.ec2.internal sh[15061]: 10.244.78.1 "GET / HTTP/1.0" 404 74 "Sensu-HTTP-Check"
Feb 18 14:33:56 ip-10-0-30-167.ec2.internal sh[15061]: WARNING public: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.3')
Feb 18 14:33:56 ip-10-0-30-167.ec2.internal sh[15061]: WARNING [public]: failed to connect to container ('Key not found : /deis/services/public/public_v43.cmd.3')
Feb 18 14:33:58 ip-10-0-30-167.ec2.internal sh[15061]: ERROR public: aborting, app containers failed to respond to health check
Feb 18 14:33:58 ip-10-0-30-167.ec2.internal sh[15061]: ERROR [public]: aborting, app containers failed to respond to health check
```

**Comment by sstarcher** [comment]
I'm going to rebuild and it watch to see if it ever appears in fleet and gets removed.

**Comment by sstarcher** [comment]
I noticed the app was exposing 2 ports so I changed it to a single port and now my registry is taking a nose dive.

The registry is backed by S3
```
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: 2016-02-18 15:14:43,021 ERROR: Exception on /v1/images/58fdb77d3ee017f317e7edf6c2fba4bf13360fe6445e6e21dc3127e195e4b467/layer [PUT]
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: Traceback (most recent call last):
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: response = self.full_dispatch_request()
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: rv = self.handle_user_exception(e)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask_cors/__init__.py", line 279, in wrapped_function
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return cors_after_request(app.make_response(f(*args, **kwargs)))
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: reraise(exc_type, exc_value, tb)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: rv = self.dispatch_request()
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return self.view_functions[rule.endpoint](**req.view_args)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 280, in wrapper
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return f(*args, **kwargs)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 37, in wrapper
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return f(*args, **kwargs)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/images.py", line 222, in put_image_layer
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: store.stream_write(layer_path, sr)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 144, in stream_write
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: raise e
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: NoMoreData: No more data after: None
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: 18/Feb/2016:15:14:43 +0000 ERROR: Exception on /v1/images/58fdb77d3ee017f317e7edf6c2fba4bf13360fe6445e6e21dc3127e195e4b467/layer [PUT]
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: Traceback (most recent call last):
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: response = self.full_dispatch_request()
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: rv = self.handle_user_exception(e)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask_cors/__init__.py", line 279, in wrapped_function
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return cors_after_request(app.make_response(f(*args, **kwargs)))
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: reraise(exc_type, exc_value, tb)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: rv = self.dispatch_request()
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return self.view_functions[rule.endpoint](**req.view_args)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 280, in wrapper
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return f(*args, **kwargs)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/toolkit.py", line 37, in wrapper
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: return f(*args, **kwargs)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/images.py", line 222, in put_image_layer
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: store.stream_write(layer_path, sr)
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: File "/usr/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 144, in stream_write
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: raise e
Feb 18 15:14:43 ip-10-0-20-95.ec2.internal sh[3218]: NoMoreData: No more data after: None
```

**Comment by nathansamson** [comment]
Try restarting your registry in this case...

Also what CoreOS / docker version are you on?

**Comment by sstarcher** [comment]
I restarted the registry, builder, controller and the same issue persists.
Deis 1.12.2, CoreOS 766.5.0, Docker version 1.7.1, build df2f73d-dirty

I'm launching a new cluster beside the old one of Deis 1.12.3.  I'll leave up the old cluster to debug the issue if you guys are interested.

**Comment by sstarcher** [comment]
I stood up a new cluster beside my old cluster using Deis 1.12.3 and it has the same `NoMoreData: No more data after: None` as my previous cluster.  I currently can't build any new releases.

I am on AWS using a stateless platform so my problem likely relates to data stored in the DB or in the S3 registry.

**Comment by obmarg** [comment]
I was on AWS stateless as well, so may well be something to do with that.  I did not have problems with a new cluster though (using the same S3 bucket, and a new RDS instance based off the old one).

**Comment by sstarcher** [comment]
I was just able to push a deis build that is a ruby heroku build pack.  I created a new app and tried to push it and still get the `No more data after: None` error.

**Comment by sstarcher** [comment]
I pointed by registry to a different S3 bucket and the issue persists so it should not be related to persistent image data.

**Comment by bacongobbler** [comment]
@sstarcher are there any logs from the docker daemon? Perhaps that could point you in the right direction.

**Comment by sstarcher** [comment]
@bacongobbler nothing on the docker daemon that has the registry running on it

**Comment by bacongobbler** [comment]
I'd try all of the data plane nodes since that's where the application images are being pulled down from.

**Comment by sstarcher** [comment]
It looks like if I switch my base image that issue goes away.

**Comment by bacongobbler** [comment]
closing as inactive/lack of docs, but if you happen to recreate this issue @obmarg please feel free to re-open. Thanks!

**Comment by sstarcher** [comment]
For the initial problem I have been able to reproduce it if my new containers fail health checks or go OOM.  The builder responds with a success and says the previous version number.
