### ISSUE TITLE
Getting 500 error when pulling large Docker image

### ISSUE THREAD

**Issue by monaka** [deis/deis#5051]
Sometime I get 500 error when I pulling large Docker image by `deis pull`

```
$ deis create insight-bitcoin                                                                                                                                                                                     
Creating Application... done, created insight-bitcoin
fatal: Not a git repository (or any of the parent directories): .git
To replace the existing git remote entry, run:
  git remote rename deis deis.old && deis git:remote -a insight-bitcoin
Error: exit status 128
```
`exit status 128` is expected.

```
$ deis pull monacoex/insight:bitcoin -a insight-bitcoin                                                                                                                                                           
Creating build... Error: 
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
```

unexpected.

The journal in controller.
```
Jun 15 02:50:46 deisNode0 sh[43666]: ERROR Internal Server Error: /v1/apps/insight-bitcoin/builds/
Jun 15 02:50:46 deisNode0 sh[43666]: Traceback (most recent call last):
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Jun 15 02:50:46 deisNode0 sh[43666]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Jun 15 02:50:46 deisNode0 sh[43666]: return view_func(*args, **kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
Jun 15 02:50:46 deisNode0 sh[43666]: return self.dispatch(request, *args, **kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
Jun 15 02:50:46 deisNode0 sh[43666]: response = self.handle_exception(exc)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
Jun 15 02:50:46 deisNode0 sh[43666]: response = handler(request, *args, **kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/views.py", line 162, in create
Jun 15 02:50:46 deisNode0 sh[43666]: return super(AppResourceViewSet, self).create(request, **kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/views.py", line 139, in create
Jun 15 02:50:46 deisNode0 sh[43666]: return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
Jun 15 02:50:46 deisNode0 sh[43666]: self.perform_create(serializer)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/viewsets.py", line 21, in perform_create
Jun 15 02:50:46 deisNode0 sh[43666]: self.post_save(obj)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/views.py", line 276, in post_save
Jun 15 02:50:46 deisNode0 sh[43666]: self.release = build.create(self.request.user)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/models.py", line 765, in create
Jun 15 02:50:46 deisNode0 sh[43666]: source_version=source_version)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/models.py", line 878, in new
Jun 15 02:50:46 deisNode0 sh[43666]: release.publish()
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/api/models.py", line 894, in publish
Jun 15 02:50:46 deisNode0 sh[43666]: publish_release(source_image, self.config.values, self.image, deis_registry)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/registry/dockerclient.py", line 119, in publish_release
Jun 15 02:50:46 deisNode0 sh[43666]: return client.publish_release(source, config, target, deis_registry)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/registry/dockerclient.py", line 53, in publish_release
Jun 15 02:50:46 deisNode0 sh[43666]: self.push("{}/{}".format(self.registry, name), tag)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/registry/dockerclient.py", line 80, in push
Jun 15 02:50:46 deisNode0 sh[43666]: log_output(stream)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/app/registry/dockerclient.py", line 103, in log_output
Jun 15 02:50:46 deisNode0 sh[43666]: for chunk in stream:
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/docker/client.py", line 217, in _stream_helper
Jun 15 02:50:46 deisNode0 sh[43666]: data = reader.read(1)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
Jun 15 02:50:46 deisNode0 sh[43666]: flush_decoder = True
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
Jun 15 02:50:46 deisNode0 sh[43666]: self.gen.throw(type, value, traceback)
Jun 15 02:50:46 deisNode0 sh[43666]: File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 231, in _error_catcher
Jun 15 02:50:46 deisNode0 sh[43666]: raise ReadTimeoutError(self._pool, None, 'Read timed out.')
Jun 15 02:50:46 deisNode0 sh[43666]: ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
Jun 15 02:50:46 deisNode0 sh[43666]: 10.0.0.6 "POST /v1/apps/insight-bitcoin/builds/ HTTP/1.0" 500 27 "Deis Client v1.12.3"
Jun 15 02:50:55 deisNode0 sh[43666]: 127.0.0.1 "GET /healthz HTTP/1.1" 200 2 "curl/7.47.0"
```

**Comment by monaka** [comment]
```
$ deisctl config platform get version
v1.13.1
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=899.17.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 899.17.0"
```

**Comment by bacongobbler** [comment]
That error indicates that the push to the internal registry is timing out. I wonder if there's an internal docker client timeout. Can you check the registry logs as well?

**Comment by monaka** [comment]
Like this. I'll try to get more full logs later.
```
$ deisctl journal registry@1
-- Logs begin at Sat 2016-06-11 14:58:31 UTC. --
Jun 15 02:59:06 deisNode0 sh[43839]: return self.get_content(path)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 165, in get_content
Jun 15 02:59:06 deisNode0 sh[43839]: return super(Storage, self).get_content(path)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/docker_registry/core/boto.py", line 132, in get_content
Jun 15 02:59:06 deisNode0 sh[43839]: if not key.exists():
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/s3/key.py", line 537, in exists
Jun 15 02:59:06 deisNode0 sh[43839]: return bool(self.bucket.lookup(self.name, headers=headers))
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 142, in lookup
Jun 15 02:59:06 deisNode0 sh[43839]: return self.get_key(key_name, headers=headers)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 192, in get_key
Jun 15 02:59:06 deisNode0 sh[43839]: key, resp = self._get_key_internal(key_name, headers, query_args_l)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/s3/bucket.py", line 199, in _get_key_internal
Jun 15 02:59:06 deisNode0 sh[43839]: query_args=query_args)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
Jun 15 02:59:06 deisNode0 sh[43839]: retry_handler=retry_handler
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1068, in make_request
Jun 15 02:59:06 deisNode0 sh[43839]: retry_handler=retry_handler)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 943, in _mexe
Jun 15 02:59:06 deisNode0 sh[43839]: response = connection.getresponse()
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
Jun 15 02:59:06 deisNode0 sh[43839]: response.begin()
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/httplib.py", line 453, in begin
Jun 15 02:59:06 deisNode0 sh[43839]: version, status, reason = self._read_status()
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
Jun 15 02:59:06 deisNode0 sh[43839]: line = self.fp.readline(_MAXLINE + 1)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/socket.py", line 480, in readline
Jun 15 02:59:06 deisNode0 sh[43839]: data = self._sock.recv(self._rbufsize)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/gevent/socket.py", line 394, in recv
Jun 15 02:59:06 deisNode0 sh[43839]: self._wait(self._read_event)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/gevent/socket.py", line 300, in _wait
Jun 15 02:59:06 deisNode0 sh[43839]: self.hub.wait(watcher)
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 348, in wait
Jun 15 02:59:06 deisNode0 sh[43839]: result = waiter.get()
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 575, in get
Jun 15 02:59:06 deisNode0 sh[43839]: return self.hub.switch()
Jun 15 02:59:06 deisNode0 sh[43839]: File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
Jun 15 02:59:06 deisNode0 sh[43839]: return greenlet.switch(self)
Jun 15 02:59:06 deisNode0 sh[43839]: timeout: timed out
Jun 15 02:59:06 deisNode0 sh[43839]: 15/Jun/2016:02:59:06 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Jun 15 02:59:06 deisNode0 sh[43839]: 10.0.0.4 - - [15/Jun/2016:02:59:06 +0000] "PUT /v1/repositories/insight-bitcoin/ HTTP/1.1" 500 291 "-" "docker/1.9.1 go/go1.4.3 git-commit/9894698 kernel/4.3.6-coreos os/linux arch/amd64"
```

**Comment by monaka** [comment]
I created the another app and pulled the same Docker image.
My controller journals logs same as before.
My registry@1 journals just a 404 error.

```
Jun 15 03:11:20 deisNode0 sh[43839]: 15/Jun/2016:03:11:20 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Jun 15 03:11:20 deisNode0 sh[43839]: 10.0.0.4 - - [15/Jun/2016:03:11:20 +0000] "GET /v2/ HTTP/1.1" 404 233 "-" "docker/1.9.1 go/go1.4.3 git-commit/9894698 kernel/4.3.6-coreos os/linux arch/amd64"
```

**Comment by monaka** [comment]
I googled and found the issue with similar logs.
https://github.com/docker/compose/issues/1045
(I think it isn't the direct solution because I know Deis doesn't use docker-compose)

There is a way to tune the timeout parameter easily? Or must I rebuild some Deis's images?

**Comment by monaka** [comment]
This issue is quite close.
https://github.com/docker/docker-py/issues/931.

https://github.com/docker/docker-py/issues/931#issuecomment-217163306
He/She uses same versions as Deis controller.

**Comment by bacongobbler** [comment]
From the registry logs it looks like a greenlet timeout similar to https://github.com/docker/docker-registry/issues/540. Try restarting the registry and try again?

**Comment by monaka** [comment]
My registry@1 didn't restart. I see it stacks on trying to connect to the store. It will takes a few days to see what happens.
Thank you @bacongobbler for your support. I'll report the result later.

**Comment by monaka** [comment]
I got new information sooner than I estimated.

My cluster become fine after restarting I `store-gateway` (and also `registry` and `controller` to make sure).
I've not figured out why the gateway hung up. So it may be the root cause but I'm not sure.

After restarting them, I retried `deis pull` and got `500 error` dozens times.
Finally the image was pushed into my registry.

I got similar logs I reported this issue in each retry. It seems some kind of timing issue available in Deis v1.

**Comment by monaka** [comment]
possibly related on #3479...?

**Comment by bacongobbler** [comment]
@monaka yes indeed this is the same issue as was reported in #3479. Were you able to resolve this by rebooting the registry?

**Comment by monaka** [comment]
No. My cluster becomes healthy temporary after restarting my registry. But this issue is reproduced after executing `deis pull` a few times.

**Comment by monaka** [comment]
Unfortunately I failed to rollback my CoreOS cluster. My Ceph storage was gone.
So I can't reproduce this issue.
I close this issue.  @bacongobbler, thanks for your support.

(I deployed Deis v2 in my instances instead.)
